### ISSUE TITLE
Provide support for external load balancer for PacBot UI

### ISSUE THREAD

**Issue by ppraghu** [tmobile/pacbot#134]
# 🙋 feature request
Currently, PacBot UI creates only an internal load balancer in front of the UI. It will be beneficial if it allowed an external load balancer to be placed. With this, I can use PacBot only using an EC2 instance created AWS, not from my ISP. I am not sure if this restriction was placed purposefully or not.

In fact, I tried creating an external ALB and used the target IP of the Target Group "pacbot-ngnix". I was able to bring up the PacBot landing page in my home computer's browser. However, the login was not working since the browser was sending the 'auth' request to the internal load balancer which was resolving only to a private IP and is not reachable from my computer. Here is the scenario: My external ALB DNS name is http://pacbot-external-alb-1838823122.us-west-2.elb.amazonaws.com. I could bring up the Landing page. But when I clicked on the Login button, the Auth request was going to: http://internal-pacbot-38153150.us-west-2.elb.amazonaws.com/api/auth/user/login
(where internal-pacbot-38153150.us-west-2.elb.amazonaws.com is the DNS name of the internal load balancer). It seems that the HTML / Angular page was hardcoded with the internal LB DNS name for certain requests.

## 🔦 Context

I was trying to install PacBot and give the URL to other interested parties in my company for demo purpose, With PacBot allowing only internal LB, I had to create an EC2 instance for those people to use. This was very constraining.

**Comment by sajeer-nooh** [comment]
This implemented this feature and is under testing now. You can expect this on the next release. What you have to do is to update value of a variable INTERNAL_ALB  to False

**Comment by ppraghu** [comment]
Thank you very much for the quick response, Sajeer. Will the current release work if I give this value in the settings/local.py and rebuild the app suite? 
INTERNAL_ALB = "False"
Or, do I need to make any other code changes in the current version of PacBot? Please advise. Also please advise the correct syntax of the line that I need to add to local.py.

**Comment by sajeer-nooh** [comment]
In the current version there is no such general setting that you can make in the local.py
But another workaround is to update the value of internal = False in the file https://github.com/tmobile/pacbot/blob/master/installer/resources/pacbot_app/alb.py#L8

This will make the default ALB to internet facing but inorder to access this you have make necessary inbound rules in security group

I hope this would do your purpose

Thank you

**Comment by sajeer-nooh** [comment]
Also rebuild will not reflect this change you have to run install command again.
This will not create new RDS, ES or others. This will update the ALB

**Comment by ppraghu** [comment]
Thanks Sajeer. Tried the steps that you advised, and it is working now! I had to open all ports (not just HTTP) in the security group of the created ALB. Opening just the port 80 was not enough (the auth request was giving 50x error until I opened all ports in the SG, I didn't spend much time in analyzing the root cause, but can do it later). Apart from this, it is a perfect workaround solution. Thanks.

**Comment by sajeer-nooh** [comment]
Hi @ppraghu 
Glad to hear that you was able to deploy it.

Regarding the ports, just opening port 80 would serve the purpose. I also tried this at from my side and it is working. I just opened port 80 to public and my SG contains default CIDR block and this one.

**Comment by ppraghu** [comment]
Thanks Sajeer.

**Comment by sonawanesangram** [comment]
@sajeer-nooh , @ppraghu : We achieved this by adding NAT Gateway to the security group. This way you don't have to open your SG to all ips.

**Comment by telesguilherme** [comment]
Hello,

I´ve tried to put the string for the load balancer  (alb.py), but when i try to login, nothing happens.

Any suggestions ?

**Comment by ppraghu** [comment]
I got this one working. I changed the value of internal = False in the alb.py, completely rebuilt the environment. The Terraform script will then create an external ALB instead of internal. The only manual thing you need to do is to add an inbound rule in the ALB's security group to allow external requests to come via port 80. (In my case, somehow I had to open up all of the ports, not just 80. I didn't get time to investigate the reason). 

Since I am experimenting with PacBot, I did not mind destroying the previous install of PacBot and installing it afresh with the Internal flag to False. Not sure if you are running a production instance. Then destroying will clean up the data.

**Comment by gabrielsoltz** [comment]
Hi, same here, 

I've tried to put the string for the load balancer (alb.py), but when i try to login, i get "Authentication Failed. Please check your credentials." (UI ERROR)

I've tryed destroying and installing again with this configuration just in case and got same behaviour. 
I'm using last version 1.3

I also tryed same deploy but with Internal True (default config) and it's working fine. 

When analysing connection from browser, i see:

```
POST http://pacbot-XXXX.eu-west-1.elb.amazonaws.com/api/auth/user/login 502 (Bad Gateway)
(anonymous) @ VM14:1
scheduleTask @ zone.js:3243
webpackJsonp.../../../../zone.js/dist/zone.js.ZoneDelegate.scheduleTask @ zone.js:410
onScheduleTask @ zone.js:301
webpackJsonp.../../../../zone.js/dist/zone.js.ZoneDelegate.scheduleTask @ zone.js:404
webpackJsonp.../../../../zone.js/dist/zone.js.Zone.scheduleTask @ zone.js:238
webpackJsonp.../../../../zone.js/dist/zone.js.Zone.scheduleMacroTask @ zone.js:261
scheduleMacroTaskWithCurrentZone @ zone.js:1245
(anonymous) @ zone.js:3276
proto.(anonymous function) @ zone.js:1569
xhr.offline.xhr.send @ offline.js:205
(anonymous) @ http.es5.js:1822
webpackJsonp.../../../../rxjs/_esm5/Observable.js.Observable._trySubscribe @ Observable.js:172
webpackJsonp.../../../../rxjs/_esm5/Observable.js.Observable.subscribe @ Observable.js:160
subscribeToResult @ subscribeToResult.js:23
webpackJsonp.../../../../rxjs/_esm5/operators/mergeMap.js.MergeMapSubscriber._innerSub @ mergeMap.js:138
webpackJsonp.../../../../rxjs/_esm5/operators/mergeMap.js.MergeMapSubscriber._tryNext @ mergeMap.js:135
webpackJsonp.../../../../rxjs/_esm5/operators/mergeMap.js.MergeMapSubscriber._next @ mergeMap.js:118
webpackJsonp.../../../../rxjs/_esm5/Subscriber.js.Subscriber.next @ Subscriber.js:95
webpackJsonp.../../../../rxjs/_esm5/observable/ScalarObservable.js.ScalarObservable._subscribe @ ScalarObservable.js:51
webpackJsonp.../../../../rxjs/_esm5/Observable.js.Observable._trySubscribe @ Observable.js:172
webpackJsonp.../../../../rxjs/_esm5/Observable.js.Observable.subscribe @ Observable.js:160
webpackJsonp.../../../../rxjs/_esm5/operators/mergeMap.js.MergeMapOperator.call @ mergeMap.js:92
webpackJsonp.../../../../rxjs/_esm5/Observable.js.Observable.subscribe @ Observable.js:157
webpackJsonp.../../../../rxjs/_esm5/operators/filter.js.FilterOperator.call @ filter.js:61
webpackJsonp.../../../../rxjs/_esm5/Observable.js.Observable.subscribe @ Observable.js:157
webpackJsonp.../../../../rxjs/_esm5/operators/map.js.MapOperator.call @ map.js:57
webpackJsonp.../../../../rxjs/_esm5/Observable.js.Observable.subscribe @ Observable.js:157
webpackJsonp.../../../../rxjs/_esm5/operators/map.js.MapOperator.call @ map.js:57
webpackJsonp.../../../../rxjs/_esm5/Observable.js.Observable.subscribe @ Observable.js:157
webpackJsonp.../../../../rxjs/_esm5/operators/catchError.js.CatchOperator.call @ catchError.js:80
webpackJsonp.../../../../rxjs/_esm5/Observable.js.Observable.subscribe @ Observable.js:157
webpackJsonp.../../../../rxjs/_esm5/operators/map.js.MapOperator.call @ map.js:57
webpackJsonp.../../../../rxjs/_esm5/Observable.js.Observable.subscribe @ Observable.js:157
webpackJsonp.../../../../rxjs/_esm5/operators/catchError.js.CatchOperator.call @ catchError.js:80
webpackJsonp.../../../../rxjs/_esm5/Observable.js.Observable.subscribe @ Observable.js:157
webpackJsonp.../../../../../src/app/landing-page/login/login.component.ts.LoginComponent.login @ login.component.ts:87
(anonymous) @ LoginComponent.ngfactory.js:106
handleEvent @ core.es5.js:11998
handleEvent @ core.es5.js:12717
dispatchEvent @ core.es5.js:8614
(anonymous) @ core.es5.js:10770
schedulerFn @ core.es5.js:3647
webpackJsonp.../../../../rxjs/_esm5/Subscriber.js.SafeSubscriber.__tryOrUnsub @ Subscriber.js:243
webpackJsonp.../../../../rxjs/_esm5/Subscriber.js.SafeSubscriber.next @ Subscriber.js:190
webpackJsonp.../../../../rxjs/_esm5/Subscriber.js.Subscriber._next @ Subscriber.js:131
webpackJsonp.../../../../rxjs/_esm5/Subscriber.js.Subscriber.next @ Subscriber.js:95
webpackJsonp.../../../../rxjs/_esm5/Subject.js.Subject.next @ Subject.js:56
webpackJsonp.../../../core/@angular/core.es5.js.EventEmitter.emit @ core.es5.js:3621
webpackJsonp.../../../../../src/app/shared/button/button.component.ts.ButtonComponent.onButtonClick @ button.component.ts:33
(anonymous) @ ButtonComponent.ngfactory.js:13
handleEvent @ core.es5.js:11998
handleEvent @ core.es5.js:12717
dispatchEvent @ core.es5.js:8614
(anonymous) @ core.es5.js:9228
(anonymous) @ platform-browser.es5.js:2648
webpackJsonp.../../../../zone.js/dist/zone.js.ZoneDelegate.invokeTask @ zone.js:423
onInvokeTask @ core.es5.js:3881
webpackJsonp.../../../../zone.js/dist/zone.js.ZoneDelegate.invokeTask @ zone.js:422
webpackJsonp.../../../../zone.js/dist/zone.js.Zone.runTask @ zone.js:195
webpackJsonp.../../../../zone.js/dist/zone.js.ZoneTask.invokeTask @ zone.js:498
invokeTask @ zone.js:1744
globalZoneAwareCallback @ zone.js:1770
Show 33 more frames

2019-05-09T16:02:19.698Z ERROR 	 HttpErrorResponse {headers: HttpHeaders, status: 502, statusText: "Bad Gateway", url: "http://pacbot-XXXX.eu-west-1.elb.amazonaws.com/api/auth/user/login", ok: false, …}
```

The only error i could find from cloudwatch is:

```
2019-05-09 16:04:53.878 INFO [auth-service,,,] 46 --- [ main] c.c.c.ConfigServicePropertySourceLocator : Fetching config from server at : http://pacbot-XXX.eu-west-1.elb.amazonaws.com/api/config

2019-05-09 15:58:19.318 INFO [auth-service,,,] 46 --- [ main] c.c.c.ConfigServicePropertySourceLocator : Connect Timeout Exception on Url - http://pacbot-XXX.eu-west-1.elb.amazonaws.com/api/config. Will be trying the next url if available
```

All containers seems to be running well...

Any clue where to continue analysing ? 

Thanks !

**Comment by sajeer-nooh** [comment]
If you make ALB internet-facing, then either you should modify the security group as well
1. Either you should provide incoming connection from all
2. Or you should add IPs of containers to SG because all services try to connect to config service from their own containers using ALB url

**Comment by gabrielsoltz** [comment]
It's not a network layer issue, i'm getting to the service ALB and the page is loading. The SG is already configured for that. 
The problem is when trying to authenticate.

**Comment by sajeer-nooh** [comment]
Firstly, you get 502 Bad gateway means the API service is not running

Secondly, 
```
2019-05-09 16:04:53.878 INFO [auth-service,,,] 46 --- [ main] c.c.c.ConfigServicePropertySourceLocator : Fetching config from server at : http://pacbot-XXX.eu-west-1.elb.amazonaws.com/api/config

2019-05-09 15:58:19.318 INFO [auth-service,,,] 46 --- [ main] c.c.c.ConfigServicePropertySourceLocator : Connect Timeout Exception on Url - http://pacbot-XXX.eu-west-1.elb.amazonaws.com/api/config. Will be trying the next url if available
```

This shows that the ECS task for Auth service is not running because it cannot connect to Config service. This happens only if the request from Auth service container is blocked. Without this no service will start as all services rely on config service(it holds all configurations)

Could you please tell me how did you confirm that all ECS service tasks are running? Was the health check healthier in target group?

Could you please list the inbound rules for **pacbot** security group?

**Comment by gabrielsoltz** [comment]
Hi @sajeer-nooh, thanks again for your answer, 

> Could you please tell me how did you confirm that all ECS service tasks are running? Was the health check healthier in target group?

I checked fargate service status, and all are ACTIVE. 

> Could you please list the inbound rules for pacbot security group?

- SG pacbot (DO-NOT-DELETE-IT - This has been created as part of pacbot installation) inbound ports are open to my public ip:  All traffic |  All |  All |  X.X.X.X/32 |

After reading your comment i double checked ALB health checks and most of the targets are unhealthy or at initial state but i couldn't find any error log beside the one i already sent:

```
2019-05-09 16:04:53.878 INFO [auth-service,,,] 46 --- [ main] c.c.c.ConfigServicePropertySourceLocator : Fetching config from server at : http://pacbot-XXX.eu-west-1.elb.amazonaws.com/api/config

2019-05-09 15:58:19.318 INFO [auth-service,,,] 46 --- [ main] c.c.c.ConfigServicePropertySourceLocator : Connect Timeout Exception on Url - http://pacbot-XXX.eu-west-1.elb.amazonaws.com/api/config. Will be trying the next url if available
```

**Comment by sajeer-nooh** [comment]
@gabrielsoltz ,
The problem is with the SG, it allows inbound traffic only from your IP,.
You should add inbound rules for all container IPs as well. Because When Auth service container hit Config service through ALB then the incoming request will be from the Auth container IP. You can get the container IPs by going to each ecs service.

Just to check, please enable Allow traffic from anywhere, wait for a few minutes and check then you will find the app working fine.

**Comment by gabrielsoltz** [comment]
Hi @sajeer-nooh the rule i sent is the one i added. The default one, the one created by terraform is also there, this is the whole config: 

All traffic |  All |  All |  172.31.0.0/16 |     <--- THIS IS MY VPC CIDR
All traffic |  All |  All |  X.X.X.X/32 |

It's not an SG problem. I just added my Public IP because i want to use it as an internet facing ALB. So i followed up this thread about changing to False internal parameter and of course i also opened my SG to mi Public IP.

**Comment by sonawanesangram** [comment]
@gabrielsoltz : Along with your public IP, you would also need to add container public IP's, as @sajeer-nooh suggested, to the SG.
Or if the containers are in private subnet, add the NAT gateways IP to the security group (this is better).

With your public IP added, you would only be able to access the UI container, API's will not work.

**Comment by gabrielsoltz** [comment]
Hi @sonawanesangram thanks ! So it was a SG problem. As you said, what was pending was to add containers public ips, my bad not much experience using ecs. the thing is that those ip are not elastic, so i think i will need to add a nat gateway so it's easy to manage. Thanks !
