### ISSUE TITLE
SSL For the Internal ELB

### ISSUE THREAD

**Issue by ghostinroot** [tmobile/pacbot#140]
# 🙋 feature request

It would be better to have documentation related to SSL implementation on the Internal ELB as PacBot has confidential information

## 🤔 Expected Behavior

[https://internal-load-balancer](https://internal-load-balancer)

## 😯 Current Behavior

[http://internal-elb](http://internal-elb)

Aha! Link: https://t-mobile1t-mobile.aha.io/features/PM-301

**Comment by sajeer-nooh** [comment]
This feature has been incorporated as part of PacBot 1.3 release. Please see the documentation for further details.
https://github.com/tmobile/pacbot/wiki/Install#how-to-setup-ssl

**Comment by johnakash** [comment]
SSL support has been released on #208
