### ISSUE TITLE
Shut down all operations with single click

### ISSUE THREAD

**Issue by twce** [tmobile/pacbot#142]
# 🙋 feature request

In order to stop all Pacbot operations I either have to run the destroy command or manually disable all CloudWatch event rules.

## 🤔 Expected Behavior

From the portal a user should be able to click a button to disable all CloudWatch rules related to Pacbot for a given account.

## 😯 Current Behavior

Current behavior does not exist.

## 💁 Possible Solution

A simple script that disables each Pacbot CloudWatch event rule.

Aha! Link: https://t-mobile1t-mobile.aha.io/features/PM-300

**Comment by santhoshigorle** [comment]
@twce  Can you please provide some additional information on future request.

In the Admin we have feature to enable/disable rules, that will take care of disabling cloud watch rules related to  Rules.

![image](https://user-images.githubusercontent.com/27745378/53658112-ce4df380-3c0c-11e9-94ec-397fa5637d50.png)

**Comment by twce** [comment]
@santhoshigorle I want to disable all rules with a single click.

**Comment by santhoshigorle** [comment]
@twce  this something not possible right now .  IF you want disable all rules, workaround would be  from the database cf_ruleInstance table set status to disabled with query.

**Comment by kaykumar** [comment]
@santhoshigorle Disabling with query is not going to disable cloud watch rules and that is what I think @twce is asking for.

@twce we can look into this in future releases.

**Comment by kaykumar** [comment]
This feature is now available in release 1.3
