### ISSUE TITLE
Spelling error UnProtetcedMongoDBAccess

### ISSUE THREAD

**Issue by 0xdabbad00** [tmobile/pacbot#16]
Fix filename "Protetced" to "Protected" at https://github.com/tmobile/pacbot/blob/master/jobs/pacman-awsrules/src/main/java/com/tmobile/cloud/awsrules/ec2/UnProtetcedMongoDBAccess.java

**Comment by santhoshigorle** [comment]
@0xdabbad00  Issue is fixed as part of 1.2 release. Please validate from your end.

**Comment by 0xdabbad00** [comment]
LGTM 👍
