### ISSUE TITLE
Java files missing error for few rules:-

### ISSUE THREAD

**Issue by AvinashV01** [tmobile/pacbot#165]
## Rules

- OS Type: Linux
- Java version:
 
 - 1.8

## Summary
Java files missing for below rules;-
1. PacMan_ElbWithPublicAccess_version-1_ApplicationElbWithPublicAccess_appelb
2. PacMan_S3GlobalAccess_version-1_S3BucketShouldnotpubliclyaccessble_s3
3. PacMan_ElasticSearchPublicAccess_version-1_ElasticSearchPublicAccessRule_elasticsearch
4. PacMan_UntaggedOrUnusedEbsRule_version-1_version-1_UntaggedOrUnusedEbsRule_volume
5. PacMan_ElbWithPublicAccess_version-1_ClassicElbWithPublicAccess_classicelb
6. All non-standard region rules

## Reproduce steps
Run this rules and check batch logs in failed section.

## Expected Results
Rule should run successfully.

## Actual Results
java.lang.ClassNotFoundException: cannot find class associated to rule

Aha! Link: https://t-mobile1t-mobile.aha.io/features/PM-337

**Comment by santhoshigorle** [comment]
@KanchanaAradhya  Can you please verify rule classes are missing for the above mentioned rules.

**Comment by kaykumar** [comment]
this is fixed in release 1.4
