### ISSUE TITLE
Spelling error MENDETORY_TAGS_KEY

### ISSUE THREAD

**Issue by 0xdabbad00** [tmobile/pacbot#17]
Fix spelling "MENDETORY" to "MANDATORY" at https://github.com/tmobile/pacbot/blob/c29e61dcd7f3be660abb547d1bb07e82ed9de823/jobs/pacman-awsrules/src/main/java/com/tmobile/cloud/awsrules/ec2/TaggingRule.java#L73

**Comment by santhoshigorle** [comment]
@0xdabbad00 Issue is fixed as part of 1.2 release. Please validate from your end.

**Comment by 0xdabbad00** [comment]
LGTM 👍
