### ISSUE TITLE
Python as language for rule scripting.

### ISSUE THREAD

**Issue by vvadymv** [tmobile/pacbot#171]
# 🙋 feature request

It would be easier to create new rules in Python for people who doesn't write code in Java :)

Aha! Link: https://t-mobile1t-mobile.aha.io/features/PM-339

**Comment by kaykumar** [comment]
You can do it with current version of the product, all you have to do is write a federated rule, which you can write as an AWS lambda function in python/go/node.js or any other language and configure the rest end point while configuring the rule.

**Comment by kaykumar** [comment]
This is available already.
