### ISSUE TITLE
Can you explain more about installation and configuration of pacbot ?

### ISSUE THREAD

**Issue by Piduna** [tmobile/pacbot#172]
First of all, i have a question about subnets. I have instances in all regions and in all aviability zones. Also, i have few subnets. What i should set in `settings/local.py` according to my AWS account ? I mean, should i show all my networks in all regions ? Right ?  If i have few VPC-s (not only default VPC). What i have to do in this case ?
Can you give some example according to `local.py` if i am using several vpc-s, az, subnets, etc ...
```
VPC = {
    "ID": "vpc-1",
    "CIDR_BLOCKS": ["10.0.0.0/16"],
    "SUBNETS": ["subnet-1", "subnet-2"]
}
```
Next question about rights. Can i create user with program access ? Which minimal policies, i have to use for this user for installing of this soft ? How much it will cost, if i see, that you will use nosql databases, mysql, ec2.medium instance ?
Next question about installing of angular:

```
npm install -g @angular/cli@1.6.8
npm WARN deprecated browserslist@2.11.3: Browserslist 2 could fail on reading Browserslist >3.0 config used in other tools.
npm WARN deprecated browserslist@1.7.7: Browserslist 2 could fail on reading Browserslist >3.0 config used in other tools.
npm WARN deprecated hoek@2.16.3: This version is no longer maintained. Please upgrade to the latest version.
npm WARN deprecated cryptiles@2.0.5: This version is no longer maintained. Please upgrade to the latest version.
npm WARN deprecated boom@2.10.1: This version is no longer maintained. Please upgrade to the latest version.
/root/.nvm/versions/node/v8.15.1/bin/ng -> /root/.nvm/versions/node/v8.15.1/lib/node_modules/@angular/cli/bin/ng

> node-sass@4.11.0 install /root/.nvm/versions/node/v8.15.1/lib/node_modules/@angular/cli/node_modules/node-sass
> node scripts/install.js

sh: 1: node: Permission denied

> uglifyjs-webpack-plugin@0.4.6 postinstall /root/.nvm/versions/node/v8.15.1/lib/node_modules/@angular/cli/node_modules/webpack/node_modules/uglifyjs-webpack-plugin
> node lib/post_install.js

sh: 1: node: Permission denied
npm WARN ajv-keywords@3.4.0 requires a peer of ajv@^6.9.1 but none is installed. You must install peer dependencies yourself.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.7 (node_modules/@angular/cli/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.7: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: node-sass@4.11.0 (node_modules/@angular/cli/node_modules/node-sass):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: node-sass@4.11.0 install: `node scripts/install.js`
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: spawn ENOENT

npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn
npm ERR! uglifyjs-webpack-plugin@0.4.6 postinstall: `node lib/post_install.js`
npm ERR! spawn ENOENT
npm ERR!
npm ERR! Failed at the uglifyjs-webpack-plugin@0.4.6 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2019-03-25T06_56_42_176Z-debug.log
```

It happens in all versions of `node` newer than `8.15.1`. I tried via `nvm`. But it is ok via `npm install -g @angular/cli`. Should i use newest angular, or should i use version, that you are showing in your guide ?

Also, i saw from your manual, that you are using `yum`. Have you suggest to use RedHat-based distrs ? Or can i use Ubuntu 18.04 ? There are no need to install `epel`, etc...

In the end of list of my question, can you write, what is making your script ? Step by step in more extended form. For example:
```
- creates groups;
- creates database via RDS
....
```

According to suggestion, can you record any video lesson according to install of PacBot ? Because installation process is not trivial. It will usefull.
Thanks for your time. You are making great job.

Aha! Link: https://t-mobile1t-mobile.aha.io/features/PM-340

**Comment by sajeer-nooh** [comment]
@Piduna 

**Query Regarding VPC**
VPC variable is expecting the vpc details under which the resources for PacBot app has to be created. This VPC should be the same as that of the EC2 instance that you create for installation. You can choose any VPC and 2 subnets of it (One private and one public subnet is preferred).

You can see more details in installer documentation, https://github.com/tmobile/pacbot/wiki/Install

**Query regarding policies**
It is enough to create user with programmatic access but with the following policies
    "AmazonS3FullAccess",
    "AmazonRDSFullAccess",
    "AWSLambdaFullAccess",
    "AmazonEC2FullAccess",
    "IAMFullAccess",
    "AmazonESFullAccess"
  This must be required to create all the required resources to install PacBot

** Nodejs Version**
We recommend to use
- Install node version 8.15.0 or higher
- Install npm version 6.4.1 or higher
- Install the following npm packages
- Install Angular-CLI version 7.1.4 or higher
- Install bower version 1.8.4 or higher

If you are facing issue with these version installations, please check with nodejs forum/community to get a resolution.

** Resources created with PacBot **
Use status command (**python manager.py status**) to see all the list of resources created once the installation is completed.
You can also view the resources created/creating at the time of installation from **installer/log/terraform_install.log** file
