### ISSUE TITLE
unable to connect to the portal

### ISSUE THREAD

**Issue by ammar-alim** [tmobile/pacbot#19]
I was able to install all resources successfully with no errors but I am unable to connect to the UI, anything I need to look at?

************************************************************************************************************************
********** Login Domain: internal-pacman-alb-uijobs-012345678.us-east-1.elb.amazonaws.com
***************** Admin: admin@pacbot.org / pacman
****************** User: user@pacbot.org / user
************************************************************************************************************************

**Comment by johnakash** [comment]
Great!! 

Could you please share the response which you are hitting the ALB URL (internal-pacman-alb-uijobs-012345678.us-east-1.elb.amazonaws.com)?

**Comment by ammar-alim** [comment]
Below is what I get.

This site can’t be reached

internal-pacman-alb-uijobs-012345678.us-east-1.elb.amazonaws.com took too long to respond.
Go to http://amazonaws.com/

Search Google for internal pacman alb uijobs 012345678 east elb amazonaws
ERR_CONNECTION_TIMED_OUT

**Comment by johnakash** [comment]
Got it!

The ALB is not an internet facing on that is why it is not accessible from outside VPC. Your can follow any of the below mentioned methods to access PacBot

- Configure VPC peering from your network to PacBot installed VPC and access (Recommended)
- Launch a window machine with RDP machine VPC and access
- Configure AWS workspace in the same VPC and access

**Comment by ammar-alim** [comment]
Thanks @johnakash I was able to get there, again good stuff keep up the good work!

**Comment by johnakash** [comment]
@ammar-alim Thats awesome!

For making sure all is in place, Could you please check the availability of index named "**exceptions**" in the elasticsearch? 

If it is not there please create the same using the following command through Dev Tools in kibana,

```
PUT exceptions
{
    "mappings": {
      "sticky_exceptions": {
        "properties": {
          "assetGroup": {
            "type": "text",
            "fields": {
              "keyword": {
                "type": "keyword",
                "ignore_above": 256
              }
            }
          },
          "dataSource": {
            "type": "text",
            "fields": {
              "keyword": {
                "type": "keyword",
                "ignore_above": 256
              }
            }
          },
          "exceptionName": {
            "type": "text",
            "fields": {
              "keyword": {
                "type": "keyword",
                "ignore_above": 256
              }
            }
          },
          "exceptionReason": {
            "type": "text",
            "fields": {
              "keyword": {
                "type": "keyword",
                "ignore_above": 256
              }
            }
          },
          "expiryDate": {
            "type": "date"
          },
          "targetTypes": {
            "properties": {
              "name": {
                "type": "text",
                "fields": {
                  "keyword": {
                    "type": "keyword",
                    "ignore_above": 256
                  }
                }
              },
              "rules": {
                "properties": {
                  "ruleId": {
                    "type": "text",
                    "fields": {
                      "keyword": {
                        "type": "keyword",
                        "ignore_above": 256
                      }
                    }
                  },
                  "ruleName": {
                    "type": "text",
                    "fields": {
                      "keyword": {
                        "type": "keyword",
                        "ignore_above": 256
                      }
                    }
                  }
                }
              }
            }
          }
        }
      }
    }
}
```
