### ISSUE TITLE
Installer script possible sets up RDS incorrectly

### ISSUE THREAD

**Issue by jacob-kinzer** [tmobile/pacbot#21]
## Summary
The install script seems to setup the RDS 'Roles' table with an incorrect type. _roleId_ is set to an _BIGINIT_ when i believe _roleId_ is actually created as an UUID.

db.sql:
![image](https://user-images.githubusercontent.com/40577885/47088183-78d7f380-d1e3-11e8-80a1-498d55e2b879.png)

UserRolesServiceImpl.createUserRole:
![image](https://user-images.githubusercontent.com/40577885/47088285-b9d00800-d1e3-11e8-9beb-bf5cffe43f5f.png)

## Reproduce steps
Run the install script creating a fresh environment and see what the type of _roleId_ is.
You can see a failure if you attempt to create a new Role in the web application.

## Expected Results
I'm assuming it should be a VARCHAR() but maybe I'm missing something.

## Actual Results
_roleId_ is set to a _BIGINT_

**Comment by anilcs81** [comment]
We will check this and get back. The issue seems to be with the incorrect table mapped.

**Comment by jacob-kinzer** [comment]
Ya it comes with the readonly and admin role but we were also trying to create a role to see if we could limit it further. It looks like an role either has read or write permissions and that is it. We mainly tried to create a role because we wanted to see if we could then look at limiting that role to say a certain asset group.

**Comment by kaykumar** [comment]
Role based access to an asset group is already in our pipeline , we shall be releasing it in upcoming versions.

**Comment by jacob-kinzer** [comment]
> Role based access to an asset group is already in our pipeline , we shall be releasing it in upcoming versions.

Awesome that is really good to hear! As Anil pointed out above this bug isn't really blocking anything because of the two roles already created so its not a big deal but we just saw it in investigating of role based access. Thanks for the information!

**Comment by anilcs81** [comment]
The table has been updated as part 1.1 release and so closing it
