### ISSUE TITLE
Installation Error

### ISSUE THREAD

**Issue by vmpowercli** [tmobile/pacbot#216]
2 error(s) occurred:
While installing the pacbot, I hit this error message. All servers are deployed in a Provate subnet and can get to internet.

* null_resource.pacbot_app_ecr_APIDockerImageBuild: Error running command '/root/pacbot/installer/data/terraform/scripts_and_files/scripts/create_docker_image_and_push_to_ecr.py': exit status 1. Output: Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/docker/client.py", line 170, in _raise_for_status
    response.raise_for_status()
  File "/usr/local/lib/python3.6/site-packages/requests/models.py", line 940, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: http+docker://localunixsocket/v1.24/images/XXXXXXXXXXXXXX.dkr.ecr.us-east-1.amazonaws.com/pacbot-microservices?force=True&noprune=False

**Comment by sajeer-nooh** [comment]
Could you please share install/log/debug.log and install/log/error.log files

**Comment by sajeer-nooh** [comment]
Please check the below 2 things

1. Installer machine has enough disk space (atleast 8 GB free disk space) to build the docker image. Most of the time build fails because of this.
2. Please check the versions installed in the installer machine with the one provided in the doc,
https://github.com/tmobile/pacbot/wiki/Install

**Comment by vmpowercli** [comment]
The VM has over 20GB free space, can you please tell me which volume needs more than 8GB space

Thank You

**Comment by vmpowercli** [comment]
Issue Closed, I re-ran on AMazon Linux 2 Server and it went fine
