### ISSUE TITLE
Email Notification Issue - nested exception is java.io.IOException: Server returned HTTP response code: 403 for URL: https://s3.amazonaws.com/pacbot-data-us-east-1-<accountnumber>/pacman-v2-email-template

### ISSUE THREAD

**Issue by ghostinroot** [tmobile/pacbot#220]
## Micro services
- Spring boot Applications:
 
 - Notification Service

## Webapp
 
- OS Type: Windows/Linux/MacOS
- Java version:
 
 - 1.8
 

## Summary
I am getting the following error in cloudwatch logs when tried to send an email using AWS SES
nested exception is java.io.IOException: Server returned HTTP response code: 403 for URL: https://s3.amazonaws.com/pacbot-data-us-east-1-<accountnumber>/pacman-v2-email-template

## Reproduce steps
1. Login as admin
2. Select an issue
3. Email this Issue
4. Enter email details
5. I am receiving "Email Not Sent" Error Message

## Expected Results
"Email Sent"

## Actual Results
"Email Not Sent"
Cloud Watch logs has the following error message: nested exception is java.io.IOException: Server returned HTTP response code: 403 for URL: https://s3.amazonaws.com/pacbot-data-us-east-1-<accountnumber>/pacman-v2-email-template

Aha! Link: https://t-mobile1t-mobile.aha.io/features/PM-365

**Comment by KanchanaAradhya** [comment]
Hi,

Can you please confirm whether these properties are set properly in your local?
https://github.com/tmobile/pacbot/wiki/Notification-Service

Thanks & Regards,
Kanchana KM

**Comment by ghostinroot** [comment]
Sorry for the late reply. I have all those settings properly configured and verified them with @sajeer-nooh and @johnakash 
I can jump on a webex session to go through those settings with you again.

**Comment by KanchanaAradhya** [comment]
Yes.We can have zoom meeting.What time you can join today?

**Comment by ghostinroot** [comment]
I’m available between 10.30am to 1.00pm EST. Let me know what works for
you. Thanks!

**Comment by KanchanaAradhya** [comment]
Tomorrow at 11.30 AM IST is fine?

**Comment by KanchanaAradhya** [comment]
You can reach out me here https://github.com/KanchanaAradhya

**Comment by KanchanaAradhya** [comment]
ping me on gitter.im user name is KanchanaAradhya

**Comment by santhoshigorle** [comment]
closing issue

**Comment by varunchandak** [comment]
How was this resolved ? I am getting **Email Not Sent** error after configuring as per below details.

```
+--------------------------------------------------+----------------------------------------------+
| cfkey                                            | value                                        |
+--------------------------------------------------+----------------------------------------------+
| spring.mail.host                                 | email-smtp.eu-west-1.amazonaws.com           |
| spring.mail.port                                 | 587                                          |
| spring.mail.protocol                             | smtp                                         |
| spring.mail.defaultEncoding                      | UTF-8                                        |
| spring.mail.username                             | AKIAXXX                                      |
| spring.mail.password                             | ABCDXXXX                                     |
| spring.mail.properties.mail.smtp.auth            | true                                         |
| spring.mail.properties.mail.smtp.ssl.trust       | email-smtp.eu-west-1.amazonaws.com           |
| spring.mail.properties.mail.smtp.starttls.enable | true                                         |
| spring.mail.test-connection                      | false                                        |
| spring.mail.host                                 | email-smtp.eu-west-1.amazonaws.com           |
+--------------------------------------------------+----------------------------------------------+
```

**Comment by varunchandak** [comment]
Also, in the cloudwatch logs, I can see this error:
```
10.9.130.25 - - [12/Feb/2020:06:18:11 +0000] "POST /api/pacman/find-jira-ticket HTTP/1.1" 405 575 "http://abc.xyz/pl/(compliance/issue-details/78h9873h94hb0497b865)?ag=aws&domain=Infra%20%26%20Platforms" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.87 Safari/537.36"
```

**Comment by varunchandak** [comment]
nevermind, it is fixed.

I had to kill all the ECS tasks for this to get working.
