### ISSUE TITLE
Adding client accounts 

### ISSUE THREAD

**Issue by ammarion** [tmobile/pacbot#24]
I have created the roles in both base and client account and made sure the trust is configured in the client account and modified the cloud watch event role with the client account number.

With that said, the UI isn't showing data from the client account where should I look for errors to troubleshoot this misery?

**Comment by johnakash** [comment]
@ammar-alim , Data collection from new account is taken care of data collection batch job execution and the same will be occurring once in an hour. So hopefully in an hour time the data will be available on the PacBot dashboard.

**Comment by johnakash** [comment]
The steps mentioned in the [documentation](https://github.com/tmobile/pacbot/wiki/Install#adding-new-aws-accounts-to-pacbot-to-monitor) is enough for onboarding new accounts to base account. 

Could you please quickly verify below points?

- Created iam role called pacman_ro (recommended) with ReadOnlyAccess (arn:aws:iam::aws:policy/ReadOnlyAccess)
- Updated trusted relation in newly created role to assume from pacman_ro in base account
- Updated pacman_ro policy in base account by adding new role arn along with the existing one
- Updated cloudwatch rule in base account with client account's number as follows,
  ```{
  "encrypt": false,
  "value": "Base_Account_ID,Client_Account_ID_1,Client_Account_ID_2",
  "key": "accountinfo"
   }

**Comment by jonshern** [comment]
believe we are talking about the file
installer/terraform/lambda-submit/function.tf

```   
 {
      "encrypt": false,
      "value": "${var.accountid},${var.client_accountid}",
      "key": "accountinfo"
    },
```
