### ISSUE TITLE
Error clicking policy violation 

### ISSUE THREAD

**Issue by kaykumar** [tmobile/pacbot#240]
As received in Gitter:

Hey guys, we are seeing an error when i believe we click on a policy violation where it looks like the compliance API is attempting to call into ES to get recommended actions but that index doesent exist, com.tmobile.pacman.api.commons.exception.ServiceException: java.lang.Exception: unable to execute post request to http://ESENDPOINT:80/recommended_actions/action/_count because Not Found, im assuming that this is just a feature that hasnt been open sourced yet? If so i can just comment out the call in our webapp so we dont see the error anymore but thought i would double check to make sure we didnt break anything

Aha! Link: https://t-mobile1t-mobile.aha.io/features/PM-371

**Comment by anilcs81** [comment]
We need to remove the UI integration for this API until the feature is supported..

**Comment by anilcs81** [comment]
This is fixed
