### ISSUE TITLE
cf_pac_updatable_fields missing inflation

### ISSUE THREAD

**Issue by jacob-kinzer** [tmobile/pacbot#244]
## Micro services
- Spring boot Applications:
 - Asset Service

## Summary
When clicking in on the _failed_ count of violators in a policy detail page the asset API will attempt to pull out data for the specific targetype out of cf_pac_updatable_fields. This table is just inflated with all_list, all_taggable, all_vulnerable, and all_patchable and not specific AWS resource target types.

Error thrown:
![image](https://user-images.githubusercontent.com/40577885/60023144-d79b1a00-965a-11e9-843e-4d009e4683ca.png)

## Reproduce steps
Click on a policy detail.
Click on the _failed_ count of violators here:
![image](https://user-images.githubusercontent.com/40577885/60023184-e681cc80-965a-11e9-8312-6a9843ab9ec1.png)
Error will show in the Asset API cloudwatch logs.

## Expected Results
Im assuming that this table should be filled out with different fields depending on which target type we are looking for, such as specific S3 fields when clicking on a list of violators for S3. 

## Actual Results
The list is returned with the default attributes and not specific target attributes.

Im not sure if the DB is just missing some inflation steps or if there is some steps i should have done in the UI to inflate this DB properly. Feel free to let me know if i just missed something or if i can provide any more information.

**Comment by anilcs81** [comment]
If the asset listing has multiple types to be returned, the API uses the table, **cf_pac_updatable_fields** to identify the common fields. You can also optionally specify the fields of a target type if needed to filter out specific fields, Otherwise all fields for the specific target type will be returned which is mostly preferred.

**Comment by jacob-kinzer** [comment]
Hey @anilcs81 i think I'm probably confused but with reading your comment it seems like when i click on the failed count as shown above in an S3 policy, that it calls into that database table looking for values for S3. This is so we can see fields that relate to S3 and not say EC2. Does that seem right?

I guess my issue is, at least ours, _cf_pac_updatable_fields_ table does not contain anything for S3 or any other AWS target type. It only has the 4 i listed above.

Looking at the DB.SQL file https://github.com/tmobile/pacbot/blob/91b6204e3e3e184bb617e4df529fc1b8d7477561/installer/resources/pacbot_app/files/DB.sql#L982
the table itself is only inflated with those types so i don't think my install failed or anything. Is there manual steps i need to take in the UI to inflate this table with properties for the specific AWS target types such as S3?
