### ISSUE TITLE
Autoscaling

### ISSUE THREAD

**Issue by MHP47** [tmobile/pacbot#254]
# ❔ Question

What's causing the auto-scaling groups to spin instances up/down?
What are the instances doing?

## 🔦 Context

About every half hour, the auto-scaling group is creating some number of instances. Most I've seen is 13 at once. What's actually driving that? Appears to be AWS Batch? Couldn't find anything in the doco's that indicates what and why.

Aha! Link: https://t-mobile1t-mobile.aha.io/features/PM-387

**Comment by sajeer-nooh** [comment]
There are 104 Cloudwatch rules running and which will trigger the batch jobs. These rules run at every hour. You will be able to disable/enable the rules, change the frequency from Pacbot UI
