### ISSUE TITLE
tags

### ISSUE THREAD

**Issue by travisd-spgi** [tmobile/pacbot#255]
# ❔ Question

Trying to figure out how to get the installer to add custom tags to all of the AWS elements that are created. Our environment requires certain things to be tagged, or else they get removed automatically by another tool.  So far I've seen some references to tags, but no obvious way to add them such that they get baked into the terraform files that are created. 

## 🔦 Context

Without tagging, I have to disable certain other security controls, or else the objects get removed quickly. Also makes tracking/troubleshooting things in a big environment difficult.

Aha! Link: https://t-mobile1t-mobile.aha.io/features/PM-388

**Comment by sajeer-nooh** [comment]
This has been implemented as part of PacBot 1.5
Please update the version and add the below dict with custom tags in local.py file

CUSTOM_RESOURCE_TAGS = [
    {'CreatedBy': "Username"},
    {'Environment': "prod"}
]

Here CreatedBy, Environment are tag names and Username, prod are tag values.

**Comment by travisd-spgi** [comment]
Thanks! We'll give it another look.
