### ISSUE TITLE
CloudWatch Rules not disabled, when turning off rules in Admin -> System Management

### ISSUE THREAD

**Issue by grumbis** [tmobile/pacbot#272]
## Micro services
- Spring boot Applications:
 
 -  Admin Service

## Rules

aws_snapshot_should_not_be_publicly_accessible
aws_EC2_should_not_be_publicly_accessible_with_any_port

## Webapp
 
- OS Type: Linux
- Java version:
 
 - 1.8
 

## Summary

When turning off CloudWatch rules, two of the rules stay enabled.

## Reproduce steps

Under Admin -> System Management -> Rules, turn the setting to off.

## Expected Results

All of the PacBot "aws_*" rules should be disabled.

## Actual Results

The following rules stay enabled.

aws_snapshot_should_not_be_publicly_accessible
aws_EC2_should_not_be_publicly_accessible_with_any_port

Aha! Link: https://t-mobile1t-mobile.aha.io/features/PM-408

**Comment by santhoshigorle** [comment]
@grumbis  did you installed latest version of PacBot, we were unable to reproduce issue.
