### ISSUE TITLE
Admin -> System Management doesn't save the Rules "Off" state.

### ISSUE THREAD

**Issue by grumbis** [tmobile/pacbot#273]
## Micro services
- Spring boot Applications:
 
 -  Admin Service

## Webapp
 
- OS Type: Linux
- Java version:
 
 - 1.8
 

## Summary

The Rules "Off" state does not appear to be saved, under Admin -> System Management.  If you navigate away from the page, it will show "On".  Clicking on this will not re-enable them, but appears to attempt to disable them once again.  If you turn them on, once the page displays them in the off state, it will re-enable them.  This could be related to https://github.com/tmobile/pacbot/issues/272 .

## Reproduce steps

Under Admin -> System Management, click the slider to turn off the Rules.  Navigate away from this page, once you navigate back to it (given enough time for the CloudWatch Rules to complete disabling).

## Expected Results

Navigating back to the Admin -> Systems Management page, should continue to show the "Off" state for Rules.

## Actual Results

Navigating back to the Admin -> Systems Management page displays the "On" state for Rules, even when they were previously disabled.

Aha! Link: https://t-mobile1t-mobile.aha.io/features/PM-409

**Comment by santhoshigorle** [comment]
unable to reproduce. Please check if you are using older versions
