### ISSUE TITLE
RDS table pac_config_key_metadata needs proper information filled out for description field.

### ISSUE THREAD

**Issue by grumbis** [tmobile/pacbot#274]
## Micro services
- Spring boot Applications:
 
 -  Admin Service

## Webapp
 
- OS Type: Linux
- Java version:
 
 - 1.8
 

## Summary

When navigating through Admin -> Configuration Management, the data pulled for the informational 'i' icons to the right of each configuration setting, has no valid data.  The values are either "Description PlaceHolder", or blank (pulled from the pac_config_key_metadata table it appears).  As there is sparse wiki documentation, and I believe this data is supposed to be filled out, I am filing it as a bug.

## Reproduce steps

Under Admin -> Configuration Management, mouseover any 'i' informational icon to the right of a configuration parameter.

## Expected Results

I expect to see full descriptions of what each parameter represents.

## Actual Results

Mouseover displays "Description PlaceHolder" or nothing at all.

Aha! Link: https://t-mobile1t-mobile.aha.io/features/PM-410

**Comment by santhoshigorle** [comment]
fixed as part of 1.6 release.
https://github.com/tmobile/pacbot/releases/tag/1.6
