### ISSUE TITLE
On the Compliance tab, the Total Tag Compliance section doesn't scale appropriately

### ISSUE THREAD

**Issue by grumbis** [tmobile/pacbot#276]
## Micro services
- Spring boot Applications:
 
 - Compliance Service

## Webapp
 
- OS Type: Linux
- Java version:
 
 - 1.8
 

## Summary

Under Compliance -> Tagging Compliance -> Total Tag Compliance on the right, when than 5 mandatory tags have been added, the graphic/text is not visible, or is cut off by the TagName/Untagged/Tagged section immediately below it.

## Reproduce steps

Under Admin -> Configuration Management -> Application, set tagging.mandatoryTags to more than 5 tags.  Then return to the Compliance -> Tagging Compliance page (after restarting necessary services) to view Total Tag Compliance section.

## Expected Results

I would expect the graphic would scale appropriately, and that all labels were visible.

## Actual Results

Graphic is skewed outside of the Total Tag Compliance section.

Aha! Link: https://t-mobile1t-mobile.aha.io/features/PM-412

**Comment by santhoshigorle** [comment]
Fixed as part of PacBot 1.6 release .
