### ISSUE TITLE
Source Code Double Download

### ISSUE THREAD

**Issue by jonshern** [tmobile/pacbot#28]
# ❔ Build Process Question

My understanding of the the Build Process steps are as follows.

- Setup Prerequisites
- Clone Source (Manually)
- Modify the Resource.json
- Start the install
  - Enter the Access Keys
  - Run the terraform to setup the core stuff 
  - Clone the Source . (Through Python using ssh)
  - Run the maven build
  - Create more infra
  - upload the payloads

In this flow the code is downloaded twice in two places.
Seems like just setting a BUILD_DIR that points to the original cloned repo, if someone wants to.

**Comment by johnakash** [comment]
This has been fixed one #45
