### ISSUE TITLE
Version of MySQL in PreRequisites

### ISSUE THREAD

**Issue by ajb1967** [tmobile/pacbot#292]
# ❔ Question
Hi I note that you require version 15.1 or higher of MySQL as noted in the pre-requisites.
I installed mysql on my Amazon linux EC2 instance from my up-to-date local packages, using 

`$ sudo yum install mysql`

it installed version as follows
`$ mysql --version`
`mysql  Ver 14.14 Distrib 5.5.62, for Linux (x86_64) using readline 5.1`

How do i get version 15.1 ? (I even looked at AWS RDS and MySQL only goes up to version 8)

Is your documentation correct ? or am I missing something ?

## 💻 Code Sample

Aha! Link: https://t-mobile1t-mobile.aha.io/features/PM-454

**Comment by sajeer-nooh** [comment]
This is mysql client version and we recommend to install from Amazon Linux.
