### ISSUE TITLE
Setting AWS Authentication Mechanism value in common.py or local.py

### ISSUE THREAD

**Issue by bsakweson** [tmobile/pacbot#296]
# ❔ Question

I noticed that there are three authentication options available for the installer. 

```
module.packbot.aws_instance.pacbot (remote-exec): 	Select AWS authentication mechanism:

module.packbot.aws_instance.pacbot (remote-exec): 	1. Using access key and secret key

module.packbot.aws_instance.pacbot (remote-exec): 	2. Assuming an IAM role

module.packbot.aws_instance.pacbot (remote-exec): 	3. Using IAM role attached to the this instance

```

Is there a property I can use in `local.py` or `common.py` files to set these values so that one is not forced to enter it on stdinput during installation?

Example would be something like:

`AUTHENTICATION_MECHANISM = 1`

Then these values would be read if they are set:

```
AWS_ACCESS_KEY = "${aws_access_key}"
AWS_SECRET_KEY = "${aws_access_secret}"
AWS_REGION = "${aws_region}"
```

**Comment by sajeer-nooh** [comment]
Right now, auth mechanism cannot be configured as we specifically want the user to be aware of these options and chose one among them during installation. It is just a matter of typing 1/2/3.

But if you choose 1 then you can use the existing configuration to proceed with the provided keys i.e.
 
`AWS_ACCESS_KEY = "Access Key"
AWS_SECRET_KEY = "Secret key"
AWS_REGION = "Region"
`

**Comment by bsakweson** [comment]
I see. The challenge here is that I am scripting the entire installation process using terraform and would prefer not to do any manual process. It turns out that when it gets to this stage, it just stalls the process.  As a user and hopefully my fellow users would see it the same way, I am struggling to see how not allowing one to set that value affects one from seeing that there are choices.

Setting a value for this would make this installation user friendlier because it give those of us who are doing infrastructure as code to script out the entire installation process in AWS [VPC, Installation Instance with all dependencies met, and then run the pacbot installation command], select our preferred `Authentication Mechanism` be it `instance profile`, `iam role` or `access key and secret` and systematically continue the process. Thanks.

**Comment by bsakweson** [comment]
Just incase somebody runs into this. Here is how I worked around this:

I replaced line 40 of `pacbot/installer/core/providers/aws/input.py` by setting the value of my authentication mechanism there. This value is parameterized and set via a template file.

**Comment by sajeer-nooh** [comment]
Hi @bsakweson 
Thanks for letting me know about your automation. I can understand your platform and I am thinking to provide an argument like --silent along with the command so that everything can be taken from the configuration and no user direct input is required. There are some more inputs required in upcoming releases. So in order to satisfy all customers, we will do this for you.

Could you please create a feature request in GitHub for this i.e. to have all configurations in settings file instead of input from user on the screen? We will take it forward from there.

Thanks
Sajeer
