### ISSUE TITLE
Pacbot installation created too many instances

### ISSUE THREAD

**Issue by bsakweson** [tmobile/pacbot#298]
# ❔ Question

Is it normal for pacbot installation to create so many instances? I checked the autoscalling group created by pacbot and saw that it has a desired number instances set to 28 and max instances set to 28. Am I missing something?

Aha! Link: https://t-mobile1t-mobile.aha.io/features/PM-461

**Comment by sajeer-nooh** [comment]
The instances spawn up because batch jobs might be running. There are 105 Cloudwatch rules which trigger the batch jobs. These jobs are designed to pull data from AWS services and put in Elasticsearch. PacBot application pulls data from this ElasticSearch data.
