### ISSUE TITLE
503 service termporarily unavailable error after successful installation

### ISSUE THREAD

**Issue by bsakweson** [tmobile/pacbot#299]
# ❔ Question

Is there an additional documentation on what needs to happen after a successful installation to successfully view the landing page?

## 🔦 Context
Pacbot Version: 1.5
I successfully install pacbot on a vpc. See except of log file below to confirm a successful installation:

```
module.packbot.aws_instance.pacbot (remote-exec): 	Terraform apply executed successfully!!! Please check installation log for more details
module.packbot.aws_instance.pacbot (remote-exec): 	Completed in 11m 48s
module.packbot.aws_instance.pacbot (remote-exec):
module.packbot.aws_instance.pacbot (remote-exec): 	************************************************* OUTPUT ************************************************
module.packbot.aws_instance.pacbot (remote-exec): 	          MySQL Host: pacbot-data.xxxxxxxxxxxxx.us-east-1.rds.amazonaws.com:3306
module.packbot.aws_instance.pacbot (remote-exec): 	            MySQL DB: pacmandata
module.packbot.aws_instance.pacbot (remote-exec): 	             ES Host: vpc-pacbot-data-xxxxxxxxxxxxx.us-east-1.es.amazonaws.com
module.packbot.aws_instance.pacbot (remote-exec): 	         Kibana Host: vpc-pacbot-data-xxxxxxxxxxxxxxxxxxxxx.us-east-1.es.amazonaws.com/_plugin/kibana/
module.packbot.aws_instance.pacbot (remote-exec): 	          Pacbot URL: http://pacbot-xxxxxxxxxx.us-east-1.elb.amazonaws.com
module.packbot.aws_instance.pacbot (remote-exec): 	               Admin: xxxxxxxxxxx@xxxxxxxxxx.com / xxxxxxxxxxxxx
module.packbot.aws_instance.pacbot (remote-exec): 	                User: pacbot@xxxxxxxxxxxx.com / test123!
module.packbot.aws_instance.pacbot (remote-exec): 	*********************************************************************************************************

```
In my `common.py` file, this value is set to `MAKE_ALB_INTERNAL = False` and I believe that is supposed to make the loadbalancer public facing.

I noticed that the loadbalancer security group created by the installation terraform script does allow traffic through port 80 for any IP. After installation completion, I noticed only one instance was running and the was no movement when I tried to access the loadbalancer url `http://pacbot-xxxxxxxxxx.us-east-1.elb.amazonaws.com`. 

I added a rule to allow traffic through the loadbalancer on port 80 from all ip addresses for testing purposes. After this change I was able to see an http 503 error.

After about an hour or so I noticed more instances were spun up, over 25 of them but I can still not hit the landing page.

Am I missing something? If not where can I find information on what I need to do next to get this going?

Aha! Link: https://t-mobile1t-mobile.aha.io/features/PM-462

**Comment by sajeer-nooh** [comment]
Could you please confirm the below things
1. All ALB health check status are in the list "200,302,401"?
2. All ECS tasks are running good without any issue?
3. Is there any error showing in ECS Task Cloudwatch log?

The instances spawn up because batch jobs might be running. There are 105 Cloudwatch rules which trigger the batch jobs. These jobs are designed to pull data from AWS services and put in Elasticsearch. PacBot application get data from this ElasticSearch.
