### ISSUE TITLE
Parameter validation failed:

### ISSUE THREAD

**Issue by nandan93** [tmobile/pacbot#30]
I have cloned the pacbot project in my aws instance with ubuntu 16.04 LTS image. I successfully installed all the dependencies mentioned in the instructions. Created a vpc and 2 subnets in different availability zones as well. Entered the vpc id,cidr and subnets in resource.json.
But when I run the "python setup_pacman.py install" I enter the access key,security key and region, It exits with the below error:

-------------------------------------
Traceback (most recent call last):
  File "setup_pacman.py", line 204, in <module>
    _get_user_managed_policies(iam, user_name)
  File "setup_pacman.py", line 114, in _get_user_managed_policies
    response = iam.list_attached_user_policies(UserName=user_name)
  File "/usr/local/lib/python2.7/dist-packages/botocore/client.py", line 314, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/usr/local/lib/python2.7/dist-packages/botocore/client.py", line 586, in _make_api_call
    api_params, operation_model, context=request_context)
  File "/usr/local/lib/python2.7/dist-packages/botocore/client.py", line 621, in _convert_to_request_dict
    api_params, operation_model)
  File "/usr/local/lib/python2.7/dist-packages/botocore/validate.py", line 291, in serialize_to_request
    raise ParamValidationError(report=report.generate_report())
botocore.exceptions.ParamValidationError: Parameter validation failed:
Invalid type for parameter UserName, value: None, type: <type 'NoneType'>, valid types: <type 'basestring'>

----------------------------------------
Kindly point me if I have done any mistake in the configuration part.

**Comment by nandan93** [comment]
any solution?

**Comment by johnakash** [comment]
@nandan93 , Please confirm if you have updated with two different zone subnets in resource.json file to install PacBot.

**Comment by nandan93** [comment]
@johnakash Yes I did update with two different zone subnets in resource.json to install.

**Comment by johnakash** [comment]
@nandan93 , We have fixed this issue in our latest installer. Could you please pull the latest code and try ti install. Please feel free to let us know if the issue is still there.
