### ISSUE TITLE
Listing assets/resources by account ID or having 1 dashboard/account.

### ISSUE THREAD

**Issue by varunchandak** [tmobile/pacbot#301]
# ❔ Question

How do I list assets/resources by account ID or have 1 dashboard/account ?

## 🔦 Context

Currently, the assets are listed for all accounts together. This gets messed up if I add 2+ accounts and gets difficult to sort.

My recommendation would be to have 1 dashboard per account so that we can generate reports/ download CSVs per account itself.

## 💻 Code Sample

Aha! Link: https://t-mobile1t-mobile.aha.io/features/PM-464

**Comment by santhoshigorle** [comment]
@varunchandak  - when you install pacbot gives you default asset group(aws-all) which includes all the accounts you have added.If you would like to see account level compliance, I would suggest you to create account based asset group. Then all the dashboards will scope to one account.

you can follow [link](https://github.com/tmobile/pacbot/wiki/Admin-Features#create-asset-group) to create asset group.

**Comment by varunchandak** [comment]
hi @santhoshigorle, I am trying to add a domain first, but unsure what needs to be added to **Configuration**
![image](https://user-images.githubusercontent.com/18713091/65578568-a3096800-df93-11e9-9551-0e07c8468239.png)

**Comment by varunchandak** [comment]
I have created the asset group but it is not visible in the drop down list.
![image](https://user-images.githubusercontent.com/18713091/65582646-6f324080-df9b-11e9-9595-2fcc63e456df.png)

**Comment by varunchandak** [comment]
Also, i can see **Asset Types Count** is 0.
![image](https://user-images.githubusercontent.com/18713091/65583043-26c75280-df9c-11e9-918e-dcc8173ce07d.png)

**Comment by santhoshigorle** [comment]
Hi Varun,
For creating Asset Group you don't need to domain. Let me take step back and explain you what domain means. PacBot has generic platform to gaze compliance for any domain. Internal Pacbot has multiple domains

- Infra & Platform (For Cloud Compliance)
- DevStandards (Development Standard Compliance)
- SOX (SOX Compliance)

Resource types are mapped with domain. So in your case just directly create asset group with what ever resource types you would like include them add config filter with accountId for which you want to create asset group.

![image](https://user-images.githubusercontent.com/27745378/65626945-2b334180-df83-11e9-824e-98f6cfbdfd14.png)
 
Select Domain
![image](https://user-images.githubusercontent.com/27745378/65626975-3a19f400-df83-11e9-8762-6392c636b289.png)

![image](https://user-images.githubusercontent.com/27745378/65627070-73526400-df83-11e9-80a6-fba9837e9946.png)


![image](https://user-images.githubusercontent.com/27745378/65627037-603f9400-df83-11e9-93e8-2c4acfdde3db.png)

**Comment by varunchandak** [comment]
Understood.

How do I delete **Target Types**, **Domains** and **Asset Groups** ?

**Comment by varunchandak** [comment]
Also, is there any way to add the same attribute to all asset types when creating asset group ? Doing it manually 1 by 1 seems to be a bit tedious.

![image](https://user-images.githubusercontent.com/18713091/65661203-a9a8e580-e04e-11e9-8956-3b82afdf05fb.png)

**Comment by santhoshigorle** [comment]
@varunchandak  I know it's tedious,  it's in our pipeline to make it better.

**Comment by varunchandak** [comment]
Thanks for the help @santhoshigorle. Closing this.
