### ISSUE TITLE
Another process is running(terraform lock is found). Please wait till it completes

### ISSUE THREAD

**Issue by shivani-hotstar** [tmobile/pacbot#315]
Due to bad internet connectivity my destroy got stopped in between .
and now when i am trying to destroy again .

Error : Another process is running(terraform lock is found). Please wait till it completes

How to find that lock here.

**Comment by sajeer-nooh** [comment]
1. Go to pacbot/installer/data/terraform folder
2. Delete file .terraform.tfstate.lock.info

**Comment by shivani-hotstar** [comment]
Thanks it worked.
