### ISSUE TITLE
How do I display mandatory tags in Tagging Compliance dashboard ?

### ISSUE THREAD

**Issue by varunchandak** [tmobile/pacbot#336]
# ❔ Question

How do I display mandatory tags here in this panel ?

## 🔦 Context

I want to use 2 (for now) mandatory tags, viz., `Environment` and `ManagedBy`. I have made changed to the rules but I want to display them here as well, so that I know the percentage count for each tag.

Also in this screenshot, `Application` tags shows 100% but tagged assets are zero.

## 💻 Code Sample

![image](https://user-images.githubusercontent.com/18713091/65856487-6963a300-e37f-11e9-8912-e65dee461e27.png)

**Comment by anilcs81** [comment]
you could specifiy the mandatory.tags config properties with "Environment,ManagedBy" which is defaulted to "Application,Environment". You may use the config management functionality in Admin Module to do so

**Comment by varunchandak** [comment]
Thanks, I have done that.

Few questions: 
1. How much time does it take to reflect in the compliance dashboard?
2. How do I manually trigger this change to reflect now ?
3. Will this be reflected across all asset groups ?

**Comment by santhoshigorle** [comment]
Rule will consider newly updated tags in the execution and depends on your rule frequency. For some reason if still not reflecting I suggest you to re-start your services just make sure everything get's refreshed.

**Comment by varunchandak** [comment]
Thanks. I was unable to find any restart switch in the console. May be I am missing something ?

Also, will this also be updated, under **Tagging Compliance**.

![image](https://user-images.githubusercontent.com/18713091/66151372-cc319480-e634-11e9-94b0-36f323233304.png)

**Comment by santhoshigorle** [comment]
from ECS try to stop tasks  for asset/compliance and it will automatically re-start.

**Comment by varunchandak** [comment]
Thanks a lot, that made sense. and it is now reflecting properly.
