### ISSUE TITLE
Install process doesnt support latest version of terraform (0.12.x)

### ISSUE THREAD

**Issue by ajb1967** [tmobile/pacbot#337]
## Micro services
- Spring boot Applications:
 
 -  Admin Service
 - Auth Service
 - Asset Service
 - Compliance Service
 - Statistics Service
 - Notification Service

## Webapp
 
- OS Type: Windows/Linux/MacOS
- Java version:
 
 - 1.9
 - 1.8
 - 1.7
 

## Summary
Install instructions say install latest version of terraform. Latest version of terraform is 0.12.x
Terraform 0.12.x introduced change to structure of resource blocks such that all tf files need to be upgraded to 0.12 version. (see https://www.terraform.io/upgrade-guides/0-12.html )

So either the pacbot install instructions should say "install terraform v 0.11.11" or the tf files need to be upgraded to be compatible with syntax employed by terraform v0.12.x

## Reproduce steps
run install using terraform version 0.12.x

## Expected Results
terraform to run without any issues

## Actual Results
terraform plan fails

**Comment by sajeer-nooh** [comment]
Terraform latest version support is under development and will be released soon.

**Comment by ajb1967** [comment]
great - maybe update the install instructions to mention that 0.11.11 is latest version of terraform currently supported ?

**Comment by santhoshigorle** [comment]
as part of  2.0 release latest version will be available
