### ISSUE TITLE
Installation aborted (lack of disk space) terraform lock is found

### ISSUE THREAD

**Issue by ajb1967** [tmobile/pacbot#338]
# ❔ Question

Please can you tell me the best way to kick off the install process again. the previous run was interrupted due to file system filling up (this has now been resolved). i believe that we got to about 86 terraform items out of ~300 created.

## 🔦 Context

I have tried running sudo python3 manager.py install but i get the "Another process is running(terraform lock is found). Please wait till it completes" message.

**Comment by sajeer-nooh** [comment]
Remove the lock by deleting the file pacbot/installer/data/terraform/.terraform.tfstate.lock.info

If you get error again, try to destroy first then install again

**Comment by ajb1967** [comment]
Thanks Sajeer, I'll give it a go.
cheers,
Andy

**Comment by ajb1967** [comment]
tried rerun after deleting lock file:

Step 5: Checking resource existence
        Resource: Aws Iam Role, name: `pacbot_ro` ............................................ [Exists]            
        Resource: Aws Iam Policy, name: `pacbot_ecs_task_exec` ............................... [Exists]            
        Resource: Aws Iam Role, name: `pacbot_run_batch` ..................................... [Exists]            
        Resource: Aws Iam Role, name: `pacbot_ecs_role` ...................................... [Exists]            
        Resource: Aws Iam Instance Profile, name: `pacbot_ecs_role_profile` .................. [Exists]            
        Resource: Aws Iam Role, name: `pacbot_lambda_basic_execution` ........................ [Exists]            
        Resource: Aws Iam Policy, name: `pacbot_ro` .......................................... [Exists]            
        Resource: Aws Iam Role, name: `pacbot` ............................................... [Exists]            
        Resource: Aws Iam Policy, name: `pacbot_pacbot-autofix` .............................. [Exists]            
        Resource: Aws Iam Policy, name: `pacbot` ............................................. [Exists]            
        Resource: Aws Security Group, name: `pacbot` ......................................... [Exists]            
        Resource: Aws Db Option Group, name: `pacbot-mysql` .................................. [Exists]            
        Resource: Aws Db Parameter Group, name: `pacbot-mysql` ............................... [Exists]            
        Resource: Aws Db Subnet Group, name: `pacbot-mysql` .................................. [Exists]            
        Resource: Aws Db Instance, identifier: `pacbot-data` ................................. [Exists]            
        Resource: Aws Cloudwatch Log Group, name: `pacbot/elasticsearch` ..................... [Exists]            
        Resource: Aws Elasticsearch Domain, domain_name: `pacbot-data` ....................... [Exists]            
        Resource: Aws Lb, name: `pacbot` ..................................................... [Exists]            
        Resource: Aws Alb Target Group, name: `pacbot-admin` ................................. [Exists]            
        Resource: Aws Alb Target Group, name: `pacbot-asset` ................................. [Exists]            
        Resource: Aws Alb Target Group, name: `pacbot-auth` .................................. [Exists]            
        Resource: Aws Alb Target Group, name: `pacbot-compliance` ............................ [Exists]            
        Resource: Aws Alb Target Group, name: `pacbot-config` ................................ [Exists]            
        Resource: Aws Alb Target Group, name: `pacbot-ngnix` ................................. [Exists]            
        Resource: Aws Alb Target Group, name: `pacbot-notifications` ......................... [Exists]            
        Resource: Aws Alb Target Group, name: `pacbot-statistics` ............................ [Exists]            
        Resource: Aws Ecr Repository, name: `pacbot-microservices` ........................... [Exists]            
        Resource: Aws Ecr Repository, name: `pacbot-webapp` .................................. [Exists]            
        Resource: Aws Cloudwatch Log Group, name: `pacbot/apis` .............................. [Exists]            
        Resource: Aws Cloudwatch Log Group, name: `pacbot/ui` ................................ [Exists]            
        Resource: Aws Ecs Task Definition, name: `pacbot-admin` .............................. [Exists]            
        Resource: Aws Ecs Task Definition, name: `pacbot-asset` .............................. [Exists]            
        Resource: Aws Ecs Task Definition, name: `pacbot-auth` ............................... [Exists]            
        Resource: Aws Ecs Task Definition, name: `pacbot-compliance` ......................... [Exists]            
        Resource: Aws Ecs Task Definition, name: `pacbot-config` ............................. [Exists]            
        Resource: Aws Ecs Task Definition, name: `pacbot-webapp` ............................. [Exists]            
        Resource: Aws Ecs Task Definition, name: `pacbot-notifications` ...................... [Exists]            
        Resource: Aws Ecs Task Definition, name: `pacbot-statistics` ......................... [Exists]            
        Resource: Aws Iam Policy, name: `pacbot_s3` .......................................... [Exists]            
        Resource: Aws Batch Compute Environment, name: `pacbot` .............................. [Exists]            
        Resource: Aws Ecr Repository, name: `pacbot-rule-engine` ............................. [Exists]            
        Resource: Aws Batch Job Queue, name: `pacbot-data` ................................... [Exists]            
        Resource: Aws Batch Job Queue, name: `pacbot-rule-engine` ............................ [Exists]            
        Resource existence check failed                                                                            
Please delete all the existing resources or change their names


tried running sudo python3 manager.py destroy 

###########################################################################################################################
#######################################  ____                                  ____  ######################################
####################################### |/||\|           PacBot               |/||\| ######################################
####################################### . || .   Infra setup and deployment   . || . ######################################
#######################################   ||                                    ||   ######################################
###########################################################################################################################


Step 1: Checking if required tools are availables
        Tool: Maven, checking ................................................................ [Found]
        Tool: Git, checking .................................................................. [Found]
        Tool: MySQL client, checking ......................................................... [Found]
        Tool: Terraform, checking ............................................................ [Found]
        Tool: Nodejs, checking ............................................................... [Found]
        Tool: npm, checking .................................................................. [Found]
        Tool: Angular, checking .............................................................. [Found]
        Tool: Yarn, checking ................................................................. [Found]
        Tool: Docker, checking ............................................................... [Found]
        Required tools are available!!!

Step 2: Checking if required python packages are available
        Package: docker, Module: Client, checking ............................................ [Found]
        Module: boto3, checking .............................................................. [Found]
        Required python packages are available!!!

Step 3: Reading required inputs from user

        Select AWS authentication mechanism: 

        1. Using access key and secret key 

        2. Assuming an IAM role

        3. Using IAM role attached to the this instance

        Type 1 or 2 or 3 to continue to create services in AWS: 1

        Please enter AWS secret key: ZZZnnnnnnABC12345GF45ABCD2QCqed3dwOuh6cX
        Required inputs are available!!!

Step 4: Terraform destroy started
        Time elapsed: 0m 1s [..Exception in thread Thread-1:                                                       
Traceback (most recent call last):
  File "/usr/lib64/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/lib64/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ec2-user/git/pacbot/installer/core/providers/aws/destroy.py", line 143, in destroy_resources
    PyTerraform.save_terraform_output()
  File "/home/ec2-user/git/pacbot/installer/core/terraform/__init__.py", line 243, in save_terraform_output
    output_dict = cls.load_terraform_output()
  File "/home/ec2-user/git/pacbot/installer/core/terraform/__init__.py", line 268, in load_terraform_output
    working_dir=Settings.TERRAFORM_DIR,
  File "/home/ec2-user/git/pacbot/installer/core/lib/python_terraform/__init__.py", line 109, in __init__
    self.read_state_file(self.state)
  File "/home/ec2-user/git/pacbot/installer/core/lib/python_terraform/__init__.py", line 419, in read_state_file
    self.tfstate = Tfstate.load_file(file_path)
  File "/home/ec2-user/git/pacbot/installer/core/lib/python_terraform/__init__.py", line 54, in load_file
    json_data = json.load(f)
  File "/usr/lib64/python3.6/json/__init__.py", line 299, in load
    parse_constant=parse_constant, object_pairs_hook=object_pairs_hook, **kw)
  File "/usr/lib64/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/usr/lib64/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib64/python3.6/json/decoder.py", line 355, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Unterminated string starting at: line 3151 column 29 (char 188406)

        Error occured, please check error log for more details                                                     
[ec2-user@ip-172-31-3-63 installer]$ 


please advise. Thanks, Andy

**Comment by sajeer-nooh** [comment]
Could you please add the below line in local.py and try to install again

SKIP_RESOURCE_EXISTENCE_CHECK = True

**Comment by sajeer-nooh** [comment]
Destroy is failing because terraform file was corrupted when disk became full.

**Comment by ajb1967** [comment]
added the line to local.py

Install program seemed to ignore local.py as the resource check happened. So, I added the line to common.py and ran again. resource check was skipped, but got the following errors:

Step 5: Terraform file generation started
        Terraform file generation completed!!!
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib64/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/lib64/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ec2-user/git/pacbot/installer/core/providers/aws/install.py", line 109, in create_resources
    self._cleanup_installation_process(dry_run)
  File "/home/ec2-user/git/pacbot/installer/core/providers/aws/install.py", line 120, in _cleanup_installation_process
    self.terraform_outputs = py_terraform.save_terraform_output()
  File "/home/ec2-user/git/pacbot/installer/core/terraform/__init__.py", line 243, in save_terraform_output
    output_dict = cls.load_terraform_output()
  File "/home/ec2-user/git/pacbot/installer/core/terraform/__init__.py", line 268, in load_terraform_output
    working_dir=Settings.TERRAFORM_DIR,
  File "/home/ec2-user/git/pacbot/installer/core/lib/python_terraform/__init__.py", line 109, in __init__
    self.read_state_file(self.state)
  File "/home/ec2-user/git/pacbot/installer/core/lib/python_terraform/__init__.py", line 419, in read_state_file
    self.tfstate = Tfstate.load_file(file_path)
  File "/home/ec2-user/git/pacbot/installer/core/lib/python_terraform/__init__.py", line 54, in load_file
    json_data = json.load(f)
  File "/usr/lib64/python3.6/json/__init__.py", line 299, in load
    parse_constant=parse_constant, object_pairs_hook=object_pairs_hook, **kw)
  File "/usr/lib64/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/usr/lib64/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib64/python3.6/json/decoder.py", line 355, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Unterminated string starting at: line 3151 column 29 (char 188406)


Step 6: Terraform init started
        Execution encountered error                                                                                
        Completed in 0m 0s
        Error occured, please check error log for more details
[ec2-user@ip-172-31-3-63 installer]$

**Comment by sajeer-nooh** [comment]
It seems terraform state file cannot be loaded, the last option is to create provider.tf file in installer/data/terraform folder and add the below lines with your keys, 

provider "aws" {
  region     = "us-west-2"
  access_key = "my-access-key"
  secret_key = "my-secret-key"
}
Then run the below command

terraform apply

If this also not working, you have to manually delete the resources created for PacBot from Aws console and try a fresh installation (remove all the files from data/terraform directory before install)

**Comment by ajb1967** [comment]
thanks will give it a go tomorrow. In case the terraform apply fails, is there an easy way to identify all the things terrafrom created in my AWS environment - are all things tagged ? or do i simply look at the logfile ?

Also, am assuming that the region in the provider.tf should be the same as the AWS region i originally ran the install script against (ie us-east-1)

**Comment by sajeer-nooh** [comment]
There are 2 ways you can see the list of resources.

1. Go to https://github.com/tmobile/pacbot/wiki/Install#list-of-aws-resources-that-will-be-created-by-the-installer. You can see the list of resources
2. Put back, **`SKIP_RESOURCE_EXISTENCE_CHECK = False`** and try to install with --dry-run as optional argument i.e. **`sudo python3 manager.py install --dry-run**`**, then you can see Exists resources in the resource existence check step. There is one more command to see the list of resources but I am not sure it would work or not as there a conflict occurred. The command is **`sudo python3 manager.py status`**
All the resources have tag **pacbot**, so you can double confirm during deletion.

Coming to your second question,
Yes the region name should be the same one that you have provided during installation

**Comment by ajb1967** [comment]
Thanks @sajeer-nooh, I was able to remove all resources and start the process again.

Will be interesting to see how big the /home file system gets as a result of the installation and maybe you could include a check of the file system size before the build starts to ensure that future installers wont run into the same issue as me ... or maybe i missed some documentation that told me i had to ensure that there was sufficient disk space ???

**Comment by ajb1967** [comment]
now i am unable to login.
I can access the internal LB address i was given at the end of the script (http://internal-pacbot-1148259803.us-east-1.elb.amazonaws.com) , but when i enter the default login credentials at the login screen , i can see from the browser developer tools that Developer Tools that the login authentication is being sent to a different loadbalancer

<img width="693" alt="Capture" src="https://user-images.githubusercontent.com/34161302/66666740-3a83e180-ec49-11e9-8aa3-cef1ffee2c64.PNG">

Could a previous install's variables be somehow screwing with this install ?

**Comment by sajeer-nooh** [comment]
Ideally this should not happen, but since you are facing issue, could you please remove the following files then got checkout -f to revert all the changes then give a redeploy

Steps

1. Remove all files in 
 pacbot/installer/data/output/status
2. Remove pacbot/webapp/src/config/configurations.ts file

3. Run git checkout -f to revert all changes

4. Go to installer and run, sudo python3 manager.py redeploy

**Comment by sajeer-nooh** [comment]
We will add disk space validation as well in upcoming release

Thanks
Sajeer

**Comment by ajb1967** [comment]
Hi Sajeer,

I got the same login authorization error. So, I decided to completely wipe the implementation and start again and ran the install with the "destroy" option. I thn gloned the repository, changed the local.py and installed. Now I get the following error when i login:

<img width="901" alt="Capture" src="https://user-images.githubusercontent.com/34161302/66757674-8eced180-ee94-11e9-9c7b-bb5d278a166f.PNG">

Starting to get weary ...

**Comment by ajb1967** [comment]
I should point out, i am not using https. I left the ALB related configurations in local.py alone i.e.

```text
# ALB related configurations
MAKE_ALB_INTERNAL = True  # False if ALB need to be public(internet facing) else True
ALB_PROTOCOL = "HTTP"
SSL_CERTIFICATE_ARN = ""  # Required only if ALB_PROTOCOL is defined as HTTPS
PACBOT_DOMAIN = ""  # Required only if you point a CNAME record to ALB ex: app.pacbot.com
```

**Comment by ajb1967** [comment]
i found three issues
1. error message in debug.log
```text
2019-10-14 15:45:49: RDS IAM Service Linked role creation: Status:False, Message: An error occurred (InvalidInput) when calling the CreateServiceLinkedRole operation: Service role name AWSServiceRoleForRDS has been taken in this account, please try a different suffix.
2019-10-14 15:45:49: ElasticSearch IAM Service Linked role creation: Status:False, Message: An error occurred (InvalidInput) when calling the CreateServiceLinkedRole operation: Service role name AWSServiceRoleForAmazonElasticsearchService has been taken in this account, please try a different suffix.
2019-10-14 15:45:49: ECS IAM Service Linked role creation: Status:False, Message: An error occurred (InvalidInput) when calling the CreateServiceLinkedRole operation: Service role name AWSServiceRoleForECS has been taken in this account, please try a different suffix.
```
2. errors relating to python version 2 not being installed - though this doesnt appear as a requisite
(i installed python 2.7 prior to latest install)

3. errors in maven_build.log  regarding .node-gyp
```text
[INFO] gyp verb command install [ '8.12.0' ]
[INFO] gyp verb install input version string "8.12.0"
[INFO] gyp verb install installing version: 8.12.0
[INFO] gyp verb install --ensure was passed, so won't reinstall if already installed
[INFO] gyp WARN EACCES user "root" does not have permission to access the dev dir "/root/.node-gyp/8.12.0"
[INFO] gyp WARN EACCES attempting to reinstall using temporary dev dir "/home/ec2-user/git/pacbot/webapp/node_modules/node-sass/.node-gyp"
[INFO] gyp verb tmpdir == cwd automatically will remove dev files after to save disk space
[INFO] gyp verb command install [ '--node_gyp_internal_noretry', '8.12.0' ]
[INFO] gyp verb install input version string "8.12.0"
[INFO] gyp verb install installing version: 8.12.0
[INFO] gyp verb install --ensure was passed, so won't reinstall if already installed
[INFO] gyp verb install version not already installed, continuing with install 8.12.0
[INFO] gyp verb ensuring nodedir is created /home/ec2-user/git/pacbot/webapp/node_modules/node-sass/.node-gyp/8.12.0
[INFO] gyp WARN install got an error, rolling back install
[INFO] gyp verb command remove [ '8.12.0' ]
[INFO] gyp verb remove using node-gyp dir: /home/ec2-user/git/pacbot/webapp/node_modules/node-sass/.node-gyp
[INFO] gyp verb remove removing target version: 8.12.0
[INFO] gyp verb remove removing development files for version: 8.12.0
[INFO] gyp WARN install got an error, rolling back install
[INFO] gyp verb command remove [ '8.12.0' ]
[INFO] gyp verb remove using node-gyp dir: /home/ec2-user/git/pacbot/webapp/node_modules/node-sass/.node-gyp
[INFO] gyp verb remove removing target version: 8.12.0
[INFO] gyp verb remove removing development files for version: 8.12.0
[INFO] gyp ERR! configure error
[INFO] gyp ERR! stack Error: EACCES: permission denied, mkdir '/home/ec2-user/git/pacbot/webapp/node_modules/node-sass/.node-gyp'
[INFO] gyp ERR! System Linux 4.14.138-89.102.amzn1.x86_64
[INFO] gyp ERR! command "/home/ec2-user/git/pacbot/webapp/node/node" "/home/ec2-user/git/pacbot/webapp/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
[INFO] gyp ERR! cwd /home/ec2-user/git/pacbot/webapp/node_modules/node-sass
[INFO] gyp ERR! node -v v8.12.0
[INFO] gyp ERR! node-gyp -v v3.8.0
[INFO] gyp ERR! not ok
[INFO] Build failed with error code: 1
```

**Comment by ajb1967** [comment]
I presume  that running this on Amazon Linux is ok ?

**Comment by sajeer-nooh** [comment]
@ajb1967 

FIrst one is not an error as the installer tries to create service linked role and if it is already there then it would add a debug message. So you can ignore it

We do not support python version 2, you can only use python3 for the installation.

Third one seems to be a valid one, but the actual error I can see as
_[INFO] gyp ERR! stack Error: EACCES: permission denied, mkdir '/home/ec2-user/git/pacbot/webapp/node_modules/node-sass/.node-gyp'_
"
It is something related to permission issue. I would suggest you to clone the code in **/opt/** directory and tries to install

To confirm your assumption, **yes** amazon linux is the recomended one.

**Comment by sajeer-nooh** [comment]
You can manually check whether the build is working or not by going to pacbot/webapp directory and run the below command
`mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V`

**Comment by ajb1967** [comment]
cloned the repo to /opt (sudo git clone ...)
ran install as sudo from /opt/pacbot/installer
same result - login screen reports "Authentication Failed. Please check your credentials"
dont see the gyp errors in the maven log
dont you have an installer docker image I could use ?

**Comment by ajb1967** [comment]
the only other thing i can think of is that somehow accessing the internal url through port forwarding setup on the aws bastion is interfering/not helping (eg. http://localhost:5080)

**Comment by ajb1967** [comment]
the users are showing up in the database ..
<img width="534" alt="Capture" src="https://user-images.githubusercontent.com/34161302/66936202-3256e800-f035-11e9-980d-5e4144c504a5.PNG">

**Comment by sajeer-nooh** [comment]
Are you able to access apis? Please see the sample api swagger url
http://{your alb domain}/api/auth/api.html

If you are not able to access the URL, please go to ECS Cluster-> Pacbot-> Tasks -> Auth and check the log file in the cloudwatch log for any error?

**Comment by sajeer-nooh** [comment]
@ajb1967 

If your issue is resolved please close this issue otherwise please do let me know.
