### ISSUE TITLE
Installer fails with npm errors

### ISSUE THREAD

**Issue by cloudsriseup** [tmobile/pacbot#339]
## Micro services
- Installer

## Rule Engine
N/A

## Rules
N/A

## ETL
N/A

## Webapp
 Installer defined.

- OS Type: Linux
- Java version:
N/A 

## Summary
Installer fails during Terraform apply via Maven errors.

## Reproduce steps
After following installation steps and placing the appropriate values in local.py, run: sudo python3 manage.py install

## Expected Results
Successful build and installation of PacBot.

## Actual Results
Maven build breaks due to lacking npm and npm dependancies

"....
[INFO] --- frontend-maven-plugin:0.0.22:npm (npm install) @ webapp ---
[INFO] Running 'npm install --color=false' in /home/ec2-user/bin/pacbot/webapp
[ERROR] npm WARN ng2-select@1.2.0 requires a peer of @angular/common@^2.3.0 but none is installed. You must install peer dependencies yourself.
[ERROR] npm WARN ng2-select@1.2.0 requires a peer of @angular/core@^2.3.0 but none is installed. You must install peer dependencies yourself.
[ERROR] npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.1.0 (node_modules/fsevents):
[ERROR] npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.1.0: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
[ERROR]
[INFO] audited 4049 packages in 4.533s
[INFO] found 1 moderate severity vulnerability
[INFO]   run `npm audit fix` to fix them, or `npm audit` for details
[INFO]
[INFO] --- frontend-maven-plugin:0.0.22:npm (npm run ng build -- --env=prod --output-hashing=all) @ webapp ---
[INFO] Running 'npm run ng build -- --env=prod --output-hashing=all --color=false' in /home/ec2-user/bin/pacbot/webapp
[INFO]
[INFO] > pacbot-spa@2.2.2 ng /home/ec2-user/bin/pacbot/webapp
[INFO] > ng "build" "--env=prod" "--output-hashing=all" "--color=false"
[INFO]
[ERROR] You are running version v8.12.0 of Node.js, which is not supported by Angular CLI 8.0+.
[ERROR] The official Node.js version that is supported is 10.9 or greater.
[ERROR]
[ERROR] Please visit https://nodejs.org/en/ to find instructions on how to update Node.js.
[ERROR] npm ERR! code ELIFECYCLE
[ERROR] npm ERR! errno 3
[ERROR] npm ERR! pacbot-spa@2.2.2 ng: `ng "build" "--env=prod" "--output-hashing=all" "--color=false"`
[ERROR] npm ERR! Exit status 3
[ERROR] npm ERR!
[ERROR] npm ERR! Failed at the pacbot-spa@2.2.2 ng script.
[ERROR] npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
[ERROR]
[ERROR] npm ERR! A complete log of this run can be found in:
[ERROR] npm ERR!     /root/.npm/_logs/2019-10-09T19_51_35_225Z-debug.log
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO]
[INFO] api-commons ....................................... SUCCESS [14.036s]
[INFO] commons ........................................... SUCCESS [37.389s]
[INFO] PacMan Commons Projects ........................... SUCCESS [0.016s]
[INFO] admin-service ..................................... SUCCESS [8.000s]
[INFO] asset-service ..................................... SUCCESS [5.216s]
[INFO] config ............................................ SUCCESS [0.526s]
[INFO] compliance-service ................................ SUCCESS [3.895s]
[INFO] notification-service .............................. SUCCESS [2.756s]
[INFO] statistics-service ................................ SUCCESS [1.781s]
[INFO] auth-service ...................................... SUCCESS [2.718s]
[INFO] vulnerability-service ............................. SUCCESS [2.068s]
[INFO] PacMan Api Projects ............................... SUCCESS [0.181s]
[INFO] inventoryFetch .................................... SUCCESS [34.765s]
[INFO] data-shipper ...................................... SUCCESS [3.252s]
[INFO] awsrules .......................................... SUCCESS [11.461s]
[INFO] pacman-rule-engine ................................ SUCCESS [9.633s]
[INFO] pacman-cloud-notifications ........................ SUCCESS [9.424s]
[INFO] recommendation-enricher ........................... SUCCESS [2.005s]
[INFO] pacman-qualys-enricher ............................ SUCCESS [1.574s]
[INFO] PacMan Jobs Projects .............................. SUCCESS [0.007s]
[INFO] PacBot UI ......................................... FAILURE [7.310s]
[INFO] PacMan ............................................ SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 2:38.656s
[INFO] Finished at: Wed Oct 09 19:51:35 UTC 2019
[INFO] Final Memory: 196M/1022M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal com.github.eirslett:frontend-maven-plugin:0.0.22:npm (npm run ng build -- --env=prod --output-hashing=all) on project webapp: Failed to run task: 'npm run ng build -- --env=prod --output-hashing=all --color=false' failed. (error code 3) -> [Help 1]
...."

**Comment by cloudsriseup** [comment]
From the system initiating the installation:
[bobby@localhost installer]$ npm --version
6.12.0
[bobby@localhost installer]$  node --version
v10.16.3

**Comment by sajeer-nooh** [comment]
Which type of instance is used to install PacBot? 

**Debugging steps**

-  Check there is memory or disk space outage
-  Please try to run npm build manually from the terminal by going to **pacbot/webapp** directory
-  If you have cloned pacbot repo in any of the home directory, move that to **/opt/pacbot** and then try

**Comment by cloudsriseup** [comment]
t2.large

**Comment by sajeer-nooh** [comment]
Try with the below versions and install from **/opt/** directory
$npm --version
6.4.1
$ node --version
v8.16.1

**Comment by sajeer-nooh** [comment]
@aparnam93 
I hope you have installed PacBot successfully.

@cloudsriseup 
Have you tried with lower versions?

**Comment by c84170ms** [comment]
facing similar errors while installing,  any help @sajeer-nooh

**Comment by sajeer-nooh** [comment]
@c84170ms 
Please tell me the node and angular versions?

**Comment by c84170ms** [comment]
[root@ip-10-10-1-81 log]# *ng version*

     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/


*Angular CLI: 6.1.4*
Node: 12.13.0
OS: linux x64
Angular:
...

Package                      Version
------------------------------------------------------
@angular-devkit/architect    0.7.4
@angular-devkit/core         0.7.4
@angular-devkit/schematics   0.7.4
@schematics/angular          0.7.4
@schematics/update           0.7.4
rxjs                         6.5.3
typescript                   2.9.2

[root@ip-10-10-1-81 log]# *node -v*
*v12.13.0*
[root@ip-10-10-1-81 log]#

**Comment by sajeer-nooh** [comment]
@c84170ms 
As I replied to the other user, please try with lower versions

$npm --version
6.4.1
$ node --version
v8.16.1

**Comment by c84170ms** [comment]
Hi Sajeer,

Increasing the instance type didnt help however installing the specific
node and npm version that you mentioned helped and the installation was
successful sometime ago. FYI -  The installation took long time as i didnt
find the specific installs of npm and node, with the default installation i
am getting the latest version.

Two issues after successful installation:

*1. Login issue* - tried both user and admin logins by clicking on the Goto
dashboard option both failed. Below screenshot is the successful message
and tried the same logins.  Even tried all possible options like user name
as admin/admin@pacbot.org and pass as admin@pacbot.org / pacman etc but no
luck.

[image: image.png]

*2. Huge no of m4.xlarge Instances auto provision: *After couple of minutes
of successful installation i see huge number of m4.xlarge instances are
creating. the count is going beyond 40 so i stared terminating them but
they keep on recreating. so end up with destroying the entire pacbot setup.
My question - I tried this setup in a brand new aws test account where
there are no resources other than the VPC and 2 subnets then why these many
m4.xlarge instances are provisioning. It is some kind of hack, someone
updated this code and taking advantage of the aws accounts?

Please advise and suggest.

Below is the instances screenshot

[image: image.png]


Hoping to hear from you.

Regards,
Madhu

**Comment by sajeer-nooh** [comment]
1. Login issue:
It take some time to start the container and application, but still, after 10 mins, you are not able to login then there might be some issue. Could you please go to Cloudwatch Log->pacbot/apis (stream) -> auth log and check it has any error?

2. Seeing many Instances:
There is bug and team is trying to fix this issue. You can follow that here,  https://github.com/tmobile/pacbot/issues/347

**Comment by c84170ms** [comment]
Hi Sajeer,

Was there any new release for existing bug fixes which i have pointed out
earlier, please let me know if it is ready for production(internal).

Hoping for a quick response.

Regards,
Madhu
