### ISSUE TITLE
Asset Dashboard not showing untagged resources

### ISSUE THREAD

**Issue by jonshern** [tmobile/pacbot#34]
## Micro services

-- Asset Service?

## Java Version

- 1.8

## Summary

Navigating to the instance dashboard assets/asset-dashboard?ag=aws&domain=Infra%20%26%20Platforms

I see the list of resource types across the middle ENI (111) - EC2 (23) When i click on one on the left i see Assets By Application and on the right i see a graph. Currently I am not see any graph or at least the graph is blank Expected Behavior: A Graph of instances is shown

On the EC2 Screen i implemented the required tags, Application and Environment I can click on the number and it takes me to the list of instances that are tagged. But for instances that are not tagged "Without Application Tagged" when I click on the number i see nothing. It takes me to a page with filters on top, and even when i remove the filters i still do not see anything. Expected Behavior: I would see a list of the untagged instances

Aha! Link: https://t-mobile1t-mobile.aha.io/features/PM-312

**Comment by santhoshigorle** [comment]
issue fixed
