### ISSUE TITLE
PackBot Dashboard not able to access by External IP

### ISSUE THREAD

**Issue by c2c-engg-20170105** [tmobile/pacbot#376]
# ❔ Question

I am unable to access PackBot Dashboard UI by the External IP.

## 🔦 Context

I have Build Packbot source code on the Amazon centos 7 machines. Its build successfully but Not able to access it outside.
Below images show the code build successfully and application deploys on the localhost. But, I want to access the PacBot application publically.
![pacbot_code_build_success](https://user-images.githubusercontent.com/26300304/69215733-7be4a680-0b90-11ea-985f-350098f195ce.png)

created Inbound rules:
![pacbotInboudRule](https://user-images.githubusercontent.com/26300304/69215849-b9493400-0b90-11ea-8be0-073de95d8697.png)

Trying to access publically 
![notabletoaccess](https://user-images.githubusercontent.com/26300304/69215874-cb2ad700-0b90-11ea-9817-233e468cd3eb.png)

Please help me.

Aha! Link: https://t-mobile1t-mobile.aha.io/features/PM-533

**Comment by sajeer-nooh** [comment]
Hi @c2c-engg-20170105 

By default PacBot installation creates load balancer which is internal and can be accessed only within the VPC network. But you can also create an internet-facing load balancer by adding the below line in your local.py
`MAKE_ALB_INTERNAL = False`

But if you make the ALB internet-facing then either you have to enable port 80 publically in **pacbot** security group or add inbound hits from the IPs of all the ECS tasks containers.

**Comment by c2c-engg-20170105** [comment]
Hi, 
I have followed all the below steps
Steps to debug:
1.	Go to ECS-> Pacbot-> Tasks
2.	Click on Config and go to the bottom of the page to see the container details
3.	Click on Cloud-watch log and check if there is any error
(You can also directly go to the CW log streams /pacbot/apis, and check config and auth tasks log)
If you are not finding any error in the logs, please take the url in the browser
http://{ALB domain}/api/admin/api.html
and check if you can access it or not.

![pacbot_site_erro](https://user-images.githubusercontent.com/26300304/70221301-1850a080-176e-11ea-8474-e63baf2578dd.png)


still not able to access pacbot.

**Comment by sajeer-nooh** [comment]
@c2c-engg-20170105 

If this is the same issue of https://github.com/tmobile/pacbot/issues/377, please close this. We can handle this in one issue, multiple issues will become difficult to manage.
