### ISSUE TITLE
PacBot not fetching data from AWS 

### ISSUE THREAD

**Issue by keerthikanthn** [tmobile/pacbot#384]
# ❔ Question

Will PacBot application  works on Private Ips ?  or It only works when deployed with Public Ips ? for any resources launched during Pacbot Installation requires Public Ips to access data from AWS? 

## 🔦 Context

We are not seeing any data after login into Pacbot application [ Which was installed under Private Ips ] 

I Installed PacBot on Companies Infrastructure which includes Private Ips to the resources created in AWS corp environment. But after login into Pacbot application , I am not able to see any data related to complaince or assets or even search . Only message I am seeing is "**Uh-oh! Something went wrong while we were fetching your data.**"

But when I launched Pacbot application with Public Ips [ VPC & Subnets ] then I am able to see the data on Pacbot.

So please advice me How to debug this issue of not getting Assets or Compliance data . The only difference in config file [ local.py ] is VPC & Subnets 

VPC & Subnets with Private IPs - Pacbot not fetching data even after 6 hours 
VPC & Subnets with Public IPs - Pacbot fetching data after 1 - 2 hours 

1. Is Public Ip are mandatory for Pacbot installations and launching ? 
2. Suggest me debugging steps like which service I need to lookup in an order ?

Your help will be appreciated!

## 💻 Code Sample
![image](https://user-images.githubusercontent.com/20115663/69675181-10a54380-106c-11ea-8cec-64565a352e29.png)

**Comment by santhoshigorle** [comment]
Public IP's not required. @sajeer-nooh  Can you help him

**Comment by sajeer-nooh** [comment]
Hi @keerthikanthn 

From the screenshot and what I could understand is, all your PacBot API services and UI setup completed successfully but the batch jobs are not running properly.

If you are using private subnets then you don't need to enable "Enable auto-assign public IP" as NAT gateway/instance take care of this but if you are using at-least one public subnet then you should enable this for batch jobs to run. This settings is not related to PacBot but this is required for AWS batch jobs in general.

Please check batch jobs section after installing without Public IP settings enabled. After an hour if you are seeing that all jobs are in **Runnable** state, then the solution to the problem can be found here,
https://aws.amazon.com/premiumsupport/knowledge-center/batch-job-stuck-runnable-status/

If this is not the case that you are facing then please do let us know.

**Comment by keerthikanthn** [comment]
Thanks for the suggestions. I figured out issue with Keypair attached to the Ec2 instance in AWS batch but I had one more question on this will be posting as  a separate question.
