### ISSUE TITLE
Is it necessary to have AdministratorAccess for pacbot installation and access dashboard ?

### ISSUE THREAD

**Issue by c2c-engg-20170105** [tmobile/pacbot#385]
# ❔ Question

**Comment by sajeer-nooh** [comment]
It is not mandatory to have administrator access to install pacbot. The role/user with which the installation would be done should have the following policies enabled

AmazonS3FullAccess, 
AmazonRDSFullAccess,
AWSLambdaFullAccess,
AmazonEC2FullAccess,
IAMFullAccess,
AmazonESFullAccess
