### ISSUE TITLE
Select new Asset Group

### ISSUE THREAD

**Issue by alexSanchez-letgo** [tmobile/pacbot#388]
# ❔ Question

Hi, 

First of all, amazing tool, thank you.

I have follow instructions to create a new Asset group. It is already created but when I want to select the group from Assets Groups I only see AWS All.

Is there any other step I have to do in order to see listed the new Asset group? Maybe wait for several time?

## 💻 Code Sample

![image](https://user-images.githubusercontent.com/51127188/69812000-9f8e9900-11ef-11ea-8984-6a20be8a2c0e.png)
![image](https://user-images.githubusercontent.com/51127188/69811957-8259ca80-11ef-11ea-8cee-7bfff48db09c.png)

**Comment by santhoshigorle** [comment]
Hi alexSanchez-letgo ,

Thanks for your feedback!
Try logout and login back.

**Comment by alexSanchez-letgo** [comment]
Hi santhoshigorle ,

I tried everything but logging out and in. It works. 

Thank you so much
