### ISSUE TITLE
Not able to access pacbot after installation - Connection refused.

### ISSUE THREAD

**Issue by spider089** [tmobile/pacbot#405]
# ❔ Question

Not able to access pacbot after installation. Getting "This site can't be reached" error and that the site refused to connect.
NOTE: The ALB is public-facing.

**Comment by sajeer-nooh** [comment]
Refer: https://github.com/tmobile/pacbot/issues/376

**Comment by spider089** [comment]
Yes I did. I changed the local.py ALB to false, but I am still not able to access the portal.

**Comment by sajeer-nooh** [comment]
After you set the value, you should change the SG inbound rules which is mentioned in  https://github.com/tmobile/pacbot/issues/376

1. If you are using private subnets(provided in local.py) to host the ECS and public subnets(which you should change manually) for ALB then you can add the EIP of NAT to SG for port 80
2. If you are using public subnets for both ECS and ALB then you should either add the ECS container IPs or allow from all public IPs for port 80
