### ISSUE TITLE
Batch Jobs failing-Data not populating in portal with error

### ISSUE THREAD

**Issue by spider089** [tmobile/pacbot#407]
Data is not auto-populating after a successful pacbot installation. Error : 

> **Uh-oh! Something went wrong while we were fetching your data.**

Other observations:
batch jobs are failing
![image](https://user-images.githubusercontent.com/32963756/72352392-787a2100-36e2-11ea-92f4-3638a8016d8f.png)

![image](https://user-images.githubusercontent.com/32963756/72352447-93e52c00-36e2-11ea-88fb-4fe188af2ffc.png)

errors for the failed jobs:
![image](https://user-images.githubusercontent.com/32963756/72352579-d0b12300-36e2-11ea-958b-628aad258726.png)

**Comment by sajeer-nooh** [comment]
Can you check the file **pacbot/rule-engine.jar** is available in S3 bucket **pacbot-data-{region}-{account-id}**? If the installation is a success then the file should be there along with all other API and Jobs jar files.

**Comment by spider089** [comment]
Yes, the file is there in the S3 bucket.

**Comment by spider089** [comment]
A few jobs succeeded this morning but still, quite a few jobs are shown as failed.

**Comment by sajeer-nooh** [comment]
The error seems to be 404(not found) which will not happen if the jars are present. So somehow the jobs are run before they are in the bucket. 
But anyway keep an eye on the jobs and check still the jobs are failing or not. You can ignore the old failed jobs.

**Comment by spider089** [comment]
The batches all moved to succeeded automatically after 4 days which is a very long time to get the application up and running for use.
Closing the issue.
