### ISSUE TITLE
Lambda Function Error

### ISSUE THREAD

**Issue by vmpowercli** [tmobile/pacbot#459]
Hello all, I have installed sucessfully in our environment but when I tried to run the Lambda function manually I get this error message.  Can you please help me out here

START RequestId: 56288e6a-8d84-4c6f-9d3a-50eca426a63d Version: $LATEST
'jobName': KeyError
Traceback (most recent call last):
  File "/var/task/pacbot-submitBatchjob.py", line 14, in lambda_handler
    return processJsonInput(event,context)
  File "/var/task/pacbot-submitBatchjob.py", line 17, in processJsonInput
    jobName =  event['jobName'] + '-job'
KeyError: 'jobName'

END RequestId: 56288e6a-8d84-4c6f-9d3a-50eca426a63d
REPORT RequestId: 56288e6a-8d84-4c6f-9d3a-50eca426a63d	Duration: 0.81 ms	Billed Duration: 100 ms	Memory Size: 128 MB	Max Memory Used: 62 MB	Init Duration: 360.77 ms

**Comment by Akashbhaskaran** [comment]
Hi @vmpowercli , the lambda function takes a set up inputs.  These are configured in the cloud watch .  Please refer the rule config to understand different params that are being passed to the lambda.  These functions will be executed  periodically based on the schedule.

**Comment by vmpowercli** [comment]
Thank you, It worked
