### ISSUE TITLE
Run installer without sudo

### ISSUE THREAD

**Issue by gabel0287** [tmobile/pacbot#46]
# 🙋 feature request

This install script should be able to be run without using sudo permissions

## 💁 Possible Solution

Don't write to files that require elevated privileges, I think right now it's just the log files, put them in the directory of the project

**Comment by johnakash** [comment]
@gabel0287 , This feature will be out in our next release.

**Comment by johnakash** [comment]
@gabel0287 , Since docker command execution needs sudo access we cannot get this done from the installer side. 

Alternative solution is grant docker command execution from normal user. How to document is mentioned below
https://docs.docker.com/install/linux/linux-postinstall/
