### ISSUE TITLE
Can't install of latest pacbot 

### ISSUE THREAD

**Issue by mrkeyongenesis** [tmobile/pacbot#483]
# ❔ Question
Can't seem to figure out how to install pacbot. This occurs when attempting to install with Terraform version v0.14.8 or v0.12. 

## 💻 Code Sample
<img width="1264" alt="Screen Shot 2021-03-17 at 5 02 23 PM" src="https://user-images.githubusercontent.com/19792479/111442762-a70ae600-8743-11eb-85c0-f31e9c48dc3a.png">

**Comment by santhoshigorle** [comment]
follow below link to get installation steps

https://github.com/tmobile/pacbot/wiki/Install
