### ISSUE TITLE
Something went wrong while we were fetching your data.

### ISSUE THREAD

**Issue by varunchandak** [tmobile/pacbot#492]
# ❔ Question

PacBot is not displaying the data in the dashboard. Screenshot below.

![image](https://user-images.githubusercontent.com/18713091/112528643-69a0fb00-8dca-11eb-8d13-58b8bce2d0df.png)

## 🔦 Context

- Installed Pacbot properly.
- Assets are visible under the assets tab.
- The dashboard is not showing any data after waiting for more than 48 hours.

#### Observation:
AWS Batch job is failing for `pacbot-rule-engine` Job. Screenshot below:
![image](https://user-images.githubusercontent.com/18713091/112528576-54c46780-8dca-11eb-9132-5aef9d5836ce.png)

Deep diving the logs in CloudWatch, I could see Java error. Screenshot below
```
2021-03-25 12:22:57 3e114a7b-bfc3-47b9-b90d-06007027ccc0 [main] ERROR c.t.p.e.RuleEngineUncaughtExceptionHandler - java.lang.StackOverflowError
```

![image](https://user-images.githubusercontent.com/18713091/112529366-33b04680-8dcb-11eb-9da4-d5176101836e.png)

Any suggestions?

**Comment by varunchandak** [comment]
This seems to be resolved as the loadbalancer endpoint was a different one in the PacBot configuration.

**Comment by bestras023** [comment]
Hi, @varunchandak Would you please let me know how you fixed in details?
Thank you.

**Comment by varunchandak** [comment]
@bestras023 loadbalancer endpoint was a different one in the PacBot configuration

**Comment by bestras023** [comment]
@varunchandak Ok, thank you.
