### ISSUE TITLE
Batch jobs not getting executed

### ISSUE THREAD

**Issue by sachin6128** [tmobile/pacbot#51]
Hello Team,

I have Pacbot operational and I see 96 pacman-batch-jobs in runnable state and 1000+ jobs in pacman-rule-engine but they are not getting executed. I can see the ECS cluster pacman-rule-engine-env_Batch_890b6ec2-2e9a-3364-ac05-a8e3ce496abe and there are no any running tasks in it. The lambda functions are getting executed every hour and I can see a bunch of EC2 instances (all healthy with proper instance profile roles) but since the jobs are not getting executed, I cannot see any data of AWS accounts. 

Can you please help to fix this or provide any guidelines? I have added 100+ AWS accounts as per installation guidelines and the setup is running for more than 2 days now.

Thanks

--

**Comment by maheshdighe** [comment]
Hi,
Modify auto-assign IP settings was there already but still I am not able to get data on PACBOT dashboard.
 
![image](https://user-images.githubusercontent.com/45825593/51176188-4f159200-18e2-11e9-914a-676118cd9522.png)

Still, batch jobs are not running.

![image](https://user-images.githubusercontent.com/45825593/51176253-74a29b80-18e2-11e9-924a-e8eb4a446a21.png)

**Comment by johnakash** [comment]
@maheshdighe  It seems to be unusual, Please let us know your availability we can have a quick session and fix your issues.

**Comment by maheshdighe** [comment]
@johnakash, Thanks for prompt response. I will wait till next release expected in few days and re-install again PACBOT. Will get in touch with you if this issue still persist.
