### ISSUE TITLE
Does Pacbot scan the cloud or the cloud infrastructure code (eg, like TF scripts)

### ISSUE THREAD

**Issue by bhuvi11** [tmobile/pacbot#518]
Hello Team,

I am trying to use pacbot and curious to know how it works.

Does it scan the cloud infrastructure or the scrips written to up the services like tf scripts?
I see we have checkov that scans the IaC files, does pacbot does the same?

**Comment by Akashbhaskaran** [comment]
It scans the cloud (AWS and Azure ) infrastructure and not the Iac scripts.

**Comment by bhuvi11** [comment]
Hello @Akashbhaskaran,

Thanks for the quick response. 
So pacbot would need authentication details for the cloud account?

**Comment by Akashbhaskaran** [comment]
Pacbot is installed in AWS . For scanning AWS resources, it requires iam roles and trust relationship configuration for role assumption . For scanning azure resources , the authentication details such as client id / client secret is required.
