### ISSUE TITLE
UnboundLocalError: local variable 'is_deleted' referenced before assignment

### ISSUE THREAD

**Issue by marcschroeter** [tmobile/pacbot#52]
I am using Amazon Linux 2 and get this error:

****************************************************************************************************
*********************************** pacbot Installation Started! ***********************************
****************************************************************************************************

Creating  baserole
Waiting for the role to refresh
Creating  baserole
baserole  creation completed
Creating  security
-- Skipping security group creation as it already exists.
Creating  s3
Creating  es
WARNING:python_terraform:error:
Creating  rds
WARNING:python_terraform:error:
Creating  redshift
Traceback (most recent call last):
  File "setup_pacman.py", line 213, in <module>
    _access_validation(assignedpolicieslist, user_name, user_arn)
  File "setup_pacman.py", line 190, in _access_validation
    awsterraformbuild._create_aws_resources(accessKey, secretKey, region)
  File "/home/ec2-user/pacbot/installer/awsterraformbuild.py", line 47, in _create_aws_resources
    if count != 2 and checkresources._check_resource(aws_access_key, aws_secret_key, region, resource, terraform) is True:
  File "/home/ec2-user/pacbot/installer/checkresources.py", line 12, in _check_resource
    return getattr(checkresources, '_check_%s' % methodname)(accessKey, secretKey, region, resource, terraform)
  File "/home/ec2-user/pacbot/installer/checkresources.py", line 245, in _check_redshift
    _remove(resource, is_deleted)
UnboundLocalError: local variable 'is_deleted' referenced before assignment

**Comment by gabel0287** [comment]
https://github.com/tmobile/pacbot/pull/49

**Comment by sajeer-nooh** [comment]
We revamped the old installation script and in which all this kind of issues have been fixed. Please try the new installer
