### ISSUE TITLE
Additional Actions - Send Email - Not working, am i missing any configuration

### ISSUE THREAD

**Issue by sreedharande** [tmobile/pacbot#53]
## Micro services
- Spring boot Applications:
 
 -  Admin Service
 - Auth Service
 - Asset Service
 - Compliance Service
 - Statistics Service
 - Notification Service

## Webapp
 
- OS Type: Windows/Linux/MacOS
- Java version:
 
 - 1.9
 - 1.8
 - 1.7

**Comment by anilcs81** [comment]
There are some configurations related to email server is not been accepted during installation. We will update the installer to get those as well.

**Comment by santhoshigorle** [comment]
@sreedharande  As part of 1,2 release notification service is enabled. Please configure rely server details in RDS then notifications from Asset/Issue details will work fine. Step to configure Rely server can be found [here](https://github.com/tmobile/pacbot/wiki/Notification-Service)
