### ISSUE TITLE
Asset Groups are not getting deleted, Is there a way to delete unwanted asset groups from UI

### ISSUE THREAD

**Issue by sreedharande** [tmobile/pacbot#54]
## Micro services
- Spring boot Applications:
 
 -  Admin Service
 - Auth Service
 - Asset Service
 - Compliance Service
 - Statistics Service
 - Notification Service

## Webapp
 
- OS Type: Windows/Linux/MacOS
- Java version:
 
 - 1.9
 - 1.8
 - 1.7
 

## Summary
Asset Groups are not getting deleted, Is there a way to delete unwanted asset groups from UI

## Reproduce steps
1. Create Asset Group, try deleting the same from UI

## Expected Results
When Deleted, Asset Group should go away from my Dashboard

## Actual Results
Saying, Deleted successfully but still showing up in UI

**Comment by marcschroeter** [comment]
i have the same issues - how can we delete asset groups

**Comment by santhoshigorle** [comment]
@sreedharande @marcschroeter  this is fixed as part of release 1.1
