### ISSUE TITLE
"Download" failing under Policy Violations 

### ISSUE THREAD

**Issue by sreedharande** [tmobile/pacbot#55]
## Micro services
- Spring boot Applications:
 
 -  Admin Service
 - Auth Service
 - Asset Service
 - Compliance Service
 - Statistics Service
 - Notification Service

## Webapp
 
- OS Type: Windows/Linux/MacOS
- Java version:
 
 - 1.9
 - 1.8
 - 1.7
 

## Summary
"Download" failing under Policy Violations 

## Reproduce steps
Compliance --> Policy Violations--> click Download

## Expected Results
All violations should be downloaded to my PC

## Actual Results
Download Failed. Please try later

**Comment by santhoshigorle** [comment]
as part of 1.1 release download issue is fixed.
