### ISSUE TITLE
Pac-bot is not compatible with java9

### ISSUE THREAD

**Issue by Leectan** [tmobile/pacbot#58]
## Micro services
- Spring boot Applications:
 
 -  Admin Service
 - Auth Service
 - Asset Service
 - Compliance Service
 - Statistics Service
 - Notification Service

## Webapp
 
- OS Type: Windows/Linux/MacOS
- Java version: 9
 
 - 1.9

 

## Reproduce steps
<sudo python setup_pacman.py install>

## Expected Results
<>

## Actual Results
After some research, looks like Java9 is breaking the whole script. 
<img width="1377" alt="screen shot 2018-11-20 at 11 11 18 am" src="https://user-images.githubusercontent.com/24819052/48786694-61de6280-ecb5-11e8-8060-c62bb602fbcc.png">

Has anyone experience this and found a work around?

**Comment by johnakash** [comment]
Hey @Leectan , PacBot is not supporting Java 9 for now and definitely it is in our roadmap for 2019 Q2.
