### ISSUE TITLE
How to create own policies and rules

### ISSUE THREAD

**Issue by marcschroeter** [tmobile/pacbot#70]
Is there a documentation how to create own policies and rules?

**Comment by kaykumar** [comment]
we will be publishing the document to WIKI with release 1.1 which is expected in next 3 weeks.

**Comment by santhoshigorle** [comment]
@marcschroeter 
we have created documented wiki documents which explains step by step on how to create rule in PacBot. 
 You will be first consumer of this document, Please give us feedback in case if you stuck in step.

**Comment by marcschroeter** [comment]
Hi Santhos, where i can find this documents? Thanks and regards, Marc

**Comment by santhoshigorle** [comment]
Documentation can be find in below link.
https://github.com/tmobile/pacbot/wiki/Write-a-new-Rule-in-PacBot

**Comment by santhoshigorle** [comment]
From the Admin users will be able to create new rules.
Documentation can be find [here](https://github.com/tmobile/pacbot/wiki/Write-a-new-Rule-in-PacBot)
