### ISSUE TITLE
Something went wrong while we were fetching your data.

### ISSUE THREAD

**Issue by vmpowercli** [tmobile/pacbot#83]
After installation, I dont see any data on the dashboard. Instead i see the below error message. Can you please help me out here.

Something went wrong while we were fetching your data.
There are no assets in this asset group

Thank you in advance.

**Comment by vmpowercli** [comment]
Need Help!!

**Comment by vmpowercli** [comment]
Can anyone help me here..Please!!..

**Comment by vmpowercli** [comment]
FYI
<img width="1398" alt="screen shot 2019-01-14 at 11 43 55 am" src="https://user-images.githubusercontent.com/21179398/51126691-c0294c80-17f1-11e9-9960-abea37c40529.png">

**Comment by johnakash** [comment]
@vmpowercli , Could you please join to Gitter for a quick chat for troubleshooting and fixing the issue?

**Comment by vmpowercli** [comment]
I would  love to .. can you please tell me how to jump on the chat as I never used it before

Thank You

**Comment by vmpowercli** [comment]
BTW.. just logged on the gitter.. please provide me your chat details

**Comment by johnakash** [comment]
Fix: https://github.com/tmobile/pacbot/issues/51
